/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/locale/locale.conf - do not edit.
 *
 * Derived crossings for locale.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/locale.h>
#include <string.h>
#include <libraries/locale.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_locale_open_catalog[] =
{
    { OC_BuiltInLanguage, EMU_TAG_CSTR, "OC_BuiltInLanguage", NULL, 0, 0, 0, 0, 0 },
    { OC_BuiltInCodeSet, EMU_TAG_U32, "OC_BuiltInCodeSet", NULL, 0, 0, 0, 0, 0 },
    { OC_Version, EMU_TAG_U32, "OC_Version", NULL, 0, 0, 0, 0, 0 },
    { OC_Language, EMU_TAG_CSTR, "OC_Language", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_locale_open_catalog =
{
    emu_tagdesc_locale_open_catalog, 4, "locale.open_catalog"
};

static void emu_object_cleanup_Catalog(APTR emu_base, APTR emu_object)
{
    struct LocaleBase *LocaleBase = emu_base;
    CloseCatalog((struct Catalog *)emu_object);
}

static void emu_object_cleanup_Locale(APTR emu_base, APTR emu_object)
{
    struct LocaleBase *LocaleBase = emu_base;
    CloseLocale((struct Locale *)emu_object);
}

int emu68k_gen_locale(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct LocaleBase *LocaleBase = base;
    (void)r; (void)guest0; (void)LocaleBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 6:  /* CloseCatalog(struct Catalog * catalog) -> void  [-36] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Catalog, 0,
                                        "Catalog", &emu_object_0, err, errlen) < 0)
            return 1;
            CloseCatalog((struct Catalog *)emu_object_0);
        emu68k_object_release(guest0, r->a[0], EMU_OBJ_Catalog);
            return 0;
    }
    case 7:  /* CloseLocale(struct Locale * locale) -> void  [-42] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 0,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            CloseLocale((struct Locale *)emu_object_0);
        emu68k_object_release(guest0, r->a[0], EMU_OBJ_Locale);
            return 0;
    }
    case 8:  /* ConvToLower(const struct Locale * locale, ULONG character) -> ULONG  [-48] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 0,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ConvToLower((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 9:  /* ConvToUpper(const struct Locale * locale, ULONG character) -> ULONG  [-54] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 0,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ConvToUpper((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 10:  /* FormatDate: no crossing [-60] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.FormatDate needs const struct DateStamp *, const struct Hook *, const struct Locale * described");
        r->d[0] = 0;
        return 1;
    case 11:  /* FormatString: no crossing [-66] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.FormatString needs returns a pointer (APTR) described");
        r->d[0] = 0;
        return 1;
    case 12:  /* GetCatalogStr(const struct Catalog * catalog, ULONG stringNum, CONST_STRPTR defaultString) -> CONST_STRPTR  [-72] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Catalog, 1,
                                        "Catalog", &emu_object_0, err, errlen) < 0)
            return 1;
        CONST_STRPTR emu_result = (CONST_STRPTR)GetCatalogStr((const struct Catalog *)emu_object_0,
              (ULONG)r->d[0],
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]));
        if (emu68k_cstr_result_to_guest(guest0, emu_result, 4096,
                                           &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 13:  /* GetLocaleStr(const struct Locale * locale, ULONG stringNum) -> CONST_STRPTR  [-78] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 0,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
        CONST_STRPTR emu_result = (CONST_STRPTR)GetLocaleStr((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
        if (emu68k_cstr_result_to_guest(guest0, emu_result, 4096,
                                           &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 14:  /* IsAlNum(const struct Locale * locale, ULONG character) -> ULONG  [-84] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsAlNum((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 15:  /* IsAlpha(const struct Locale * locale, ULONG character) -> ULONG  [-90] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsAlpha((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 16:  /* IsCntrl(const struct Locale * locale, ULONG character) -> ULONG  [-96] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsCntrl((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 17:  /* IsDigit(const struct Locale * locale, ULONG character) -> ULONG  [-102] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsDigit((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 18:  /* IsGraph(const struct Locale * locale, ULONG character) -> ULONG  [-108] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsGraph((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 19:  /* IsLower(const struct Locale * locale, ULONG character) -> ULONG  [-114] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsLower((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 20:  /* IsPrint(const struct Locale * locale, ULONG character) -> ULONG  [-120] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsPrint((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 21:  /* IsPunct(const struct Locale * locale, ULONG character) -> ULONG  [-126] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsPunct((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 22:  /* IsSpace(const struct Locale * locale, ULONG character) -> ULONG  [-132] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsSpace((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 23:  /* IsUpper(const struct Locale * locale, ULONG character) -> ULONG  [-138] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsUpper((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 24:  /* IsXDigit(const struct Locale * locale, ULONG character) -> ULONG  [-144] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsXDigit((const struct Locale *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 25:  /* OpenCatalogA(const struct Locale * locale, CONST_STRPTR name, const struct TagItem * tags) -> struct Catalog *  [-150] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
        struct TagItem emu_tags_2[9];
        if (emu68k_tags_to_native(guest0, r->a[2], &emu_tagdomain_locale_open_catalog, emu_tags_2, 9, NULL, 0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)OpenCatalogA((const struct Locale *)emu_object_0,
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]),
              (const struct TagItem *)(r->a[2] ? emu_tags_2 : NULL));
        if (emu68k_object_to_guest(guest0, emu_result, EMU_OBJ_Catalog,
                                      base, emu_object_cleanup_Catalog,
                                      "Catalog", &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 26:  /* OpenLocale(CONST_STRPTR name) -> struct Locale *  [-156] */
    {
        APTR emu_result = (APTR)OpenLocale((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]));
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_Locale,
                                             base, emu_object_cleanup_Locale,
                                             "Locale", M68K_Locale_SIZEOF,
                                             emu_fields_Locale, EMU_NFIELDS(emu_fields_Locale),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 27:  /* ParseDate: no crossing [-162] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.ParseDate needs struct DateStamp *, struct Hook *, struct Locale * described");
        r->d[0] = 0;
        return 1;
    case 28:  /* LocalePrefsUpdate(struct Locale * locale) -> struct Locale *  [-168] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)LocalePrefsUpdate((struct Locale *)emu_object_0);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_Locale,
                                             base, NULL,
                                             "Locale", M68K_Locale_SIZEOF,
                                             emu_fields_Locale, EMU_NFIELDS(emu_fields_Locale),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 29:  /* StrConvert: no crossing [-174] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.StrConvert needs APTR buffer, const struct Locale * described");
        r->d[0] = 0;
        return 1;
    case 30:  /* StrnCmp(const struct Locale * locale, CONST_STRPTR string1, CONST_STRPTR string2, LONG length, ULONG type) -> LONG  [-180] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Locale, 1,
                                        "Locale", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)StrnCmp((const struct Locale *)emu_object_0,
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[2]),
              (LONG)r->d[0],
              (ULONG)r->d[1]);
            return 0;
    }
    case 31:  /* LocRawDoFmt: no crossing [-186] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocRawDoFmt needs private described");
        r->d[0] = 0;
        return 1;
    case 32:  /* LocStrnicmp: no crossing [-192] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocStrnicmp needs private described");
        r->d[0] = 0;
        return 1;
    case 33:  /* LocStricmp: no crossing [-198] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocStricmp needs private described");
        r->d[0] = 0;
        return 1;
    case 34:  /* LocToLower: no crossing [-204] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocToLower needs private described");
        r->d[0] = 0;
        return 1;
    case 35:  /* LocToUpper: no crossing [-210] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocToUpper needs private described");
        r->d[0] = 0;
        return 1;
    case 36:  /* LocDateToStr: no crossing [-216] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocDateToStr needs private described");
        r->d[0] = 0;
        return 1;
    case 37:  /* LocStrToDate: no crossing [-222] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocStrToDate needs private described");
        r->d[0] = 0;
        return 1;
    case 38:  /* LocDosGetLocalizedString: no crossing [-228] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocDosGetLocalizedString needs private described");
        r->d[0] = 0;
        return 1;
    case 39:  /* LocVNewRawDoFmt: no crossing [-234] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: locale.library.LocVNewRawDoFmt needs private described");
        r->d[0] = 0;
        return 1;
    }
    return 1;   /* no safe generated crossing for this vector */
}
