/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathieeesingbas/mathieeesingbas.conf - do not edit.
 *
 * Derived crossings for mathieeesingbas.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/mathieeesingbas.h>

#include "emu68k_gen.h"

int emu68k_gen_mathieeesingbas(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *MathIeeeSingBasBase = base;
    (void)r; (void)guest0; (void)MathIeeeSingBasBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 5:  /* IEEESPFix(LONG y) -> LONG  [-30] */
        r->d[0] = (ULONG)IEEESPFix((LONG)r->d[0]);
        return 0;
    case 6:  /* IEEESPFlt(LONG y) -> LONG  [-36] */
        r->d[0] = (ULONG)IEEESPFlt((LONG)r->d[0]);
        return 0;
    case 7:  /* IEEESPCmp(LONG y, LONG z) -> LONG  [-42] */
        r->d[0] = (ULONG)IEEESPCmp((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 8:  /* IEEESPTst(LONG y) -> LONG  [-48] */
        r->d[0] = (ULONG)IEEESPTst((LONG)r->d[0]);
        return 0;
    case 9:  /* IEEESPAbs(LONG y) -> LONG  [-54] */
        r->d[0] = (ULONG)IEEESPAbs((LONG)r->d[0]);
        return 0;
    case 10:  /* IEEESPNeg(LONG y) -> LONG  [-60] */
        r->d[0] = (ULONG)IEEESPNeg((LONG)r->d[0]);
        return 0;
    case 11:  /* IEEESPAdd(LONG y, LONG z) -> LONG  [-66] */
        r->d[0] = (ULONG)IEEESPAdd((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 12:  /* IEEESPSub(LONG y, LONG z) -> LONG  [-72] */
        r->d[0] = (ULONG)IEEESPSub((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 13:  /* IEEESPMul(LONG y, LONG z) -> LONG  [-78] */
        r->d[0] = (ULONG)IEEESPMul((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 14:  /* IEEESPDiv(LONG y, LONG z) -> LONG  [-84] */
        r->d[0] = (ULONG)IEEESPDiv((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 15:  /* IEEESPFloor(LONG y) -> LONG  [-90] */
        r->d[0] = (ULONG)IEEESPFloor((LONG)r->d[0]);
        return 0;
    case 16:  /* IEEESPCeil(LONG y) -> LONG  [-96] */
        r->d[0] = (ULONG)IEEESPCeil((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
