/* GENERATED by graft/gen-emu68k-bridge from rom/graphics/graphics.conf - do not edit.
 *
 * Tier 1 crossings for graphics.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/graphics.h>

#include "emu68k_gen.h"

int emu68k_gen_graphics(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct GfxBase *GfxBase = base;
    (void)r; (void)guest0; (void)GfxBase;

    switch (lvo)
    {
    case 38:  /* WaitBlit(void) -> void  [-228] */
        WaitBlit();
        return 0;
    case 45:  /* WaitTOF(void) -> void  [-270] */
        WaitTOF();
        return 0;
    case 64:  /* VBeamPos(void) -> LONG  [-384] */
        r->d[0] = (ULONG)VBeamPos();
        return 0;
    case 69:  /* FreeSprite(WORD pick) -> void  [-414] */
        FreeSprite((WORD)r->d[0]);
        return 0;
    case 76:  /* OwnBlitter(void) -> void  [-456] */
        OwnBlitter();
        return 0;
    case 77:  /* DisownBlitter(void) -> void  [-462] */
        DisownBlitter();
        return 0;
    case 114:  /* ScalerDiv(UWORD factor, UWORD numerator, UWORD denominator) -> UWORD  [-684] */
        r->d[0] = (ULONG)ScalerDiv((UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2]);
        return 0;
    case 122:  /* NextDisplayInfo(ULONG last_ID) -> ULONG  [-732] */
        r->d[0] = (ULONG)NextDisplayInfo((ULONG)r->d[0]);
        return 0;
    case 133:  /* ModeNotAvailable(ULONG modeID) -> ULONG  [-798] */
        r->d[0] = (ULONG)ModeNotAvailable((ULONG)r->d[0]);
        return 0;
    case 148:  /* SetChipRev(ULONG ChipRev) -> ULONG  [-888] */
        r->d[0] = (ULONG)SetChipRev((ULONG)r->d[0]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
