/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/iffparse/iffparse.conf - do not edit.
 *
 * Derived crossings for iffparse.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/iffparse.h>

#include "emu68k_gen.h"

int emu68k_gen_iffparse(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *IFFParseBase = base;
    (void)r; (void)guest0; (void)IFFParseBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 43:  /* GoodID(LONG id) -> LONG  [-258] */
        r->d[0] = (ULONG)GoodID((LONG)r->d[0]);
        return 0;
    case 44:  /* GoodType(LONG type) -> LONG  [-264] */
        r->d[0] = (ULONG)GoodType((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
