/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/diskfont/diskfont.conf - do not edit.
 *
 * Tier 1 crossings for diskfont.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/diskfont.h>

#include "emu68k_gen.h"

int emu68k_gen_diskfont(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *DiskfontBase = base;
    (void)r; (void)guest0; (void)DiskfontBase;

    switch (lvo)
    {
    case 6:  /* AvailFonts(STRPTR buffer, LONG bufBytes, LONG flags) -> LONG  [-36] */
        r->d[0] = (ULONG)AvailFonts((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
