/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/diskfont/diskfont.conf - do not edit.
 *
 * Derived crossings for diskfont.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/diskfont.h>

#include "emu68k_gen.h"

int emu68k_gen_diskfont(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *DiskfontBase = base;
    (void)r; (void)guest0; (void)DiskfontBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 6:  /* AvailFonts(STRPTR buffer, LONG bufBytes, LONG flags) -> LONG  [-36] */
        r->d[0] = (ULONG)AvailFonts((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
