/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/diskfont/diskfont.conf - do not edit.
 *
 * Derived crossings for diskfont.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/diskfont.h>
#include <string.h>
#include <stdio.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

int emu68k_gen_diskfont(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *DiskfontBase = base;
    (void)r; (void)guest0; (void)DiskfontBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 5:  /* OpenDiskFont(struct TextAttr * textAttr) -> struct TextFont *  [-30] */
    {
        struct TextAttr emu_struct_0;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: OpenDiskFont.textAttr requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[0], M68K_TextAttr_SIZEOF,
                                         "OpenDiskFont.textAttr", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->a[0], &emu_struct_0,
                             emu_fields_TextAttr, EMU_NFIELDS(emu_fields_TextAttr), M68K_TextAttr_SIZEOF);
        APTR emu_result = (APTR)OpenDiskFont((struct TextAttr *)&emu_struct_0);
        if (!emu_result)
        {
            struct TextAttr emu_fallback_attr = emu_struct_0;
            emu_fallback_attr.ta_Name = (STRPTR)"Vera Mono.font";
            emu_result = (APTR)OpenDiskFont((struct TextAttr *)&emu_fallback_attr);
        }
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_TextFont,
                                             base, NULL,
                                             "TextFont", 116 + 64,
                                             emu_fields_TextFont, EMU_NFIELDS(emu_fields_TextFont),
                                             &r->d[0], err, errlen) < 0)
            return 1;
        if (emu_result && r->d[0])
        {
            struct TextFont *emu_facade_native = (struct TextFont *)emu_result;
            ULONG emu_nested_guest_0 = r->d[0] + 116;
            emu68k_cstr_to_guest(guest0, emu_nested_guest_0,
                emu_facade_native->tf_Message.mn_Node.ln_Name, 64);
            emu68k_scalar_to_guest(guest0,
                r->d[0] + M68K_TextFont_tf_Message_mn_Node_ln_Name, 4,
                emu_facade_native->tf_Message.mn_Node.ln_Name ? emu_nested_guest_0 : 0);
        }
            return 0;
    }
    case 6:  /* AvailFonts(STRPTR buffer, LONG bufBytes, LONG flags) -> LONG  [-36] */
        r->d[0] = (ULONG)AvailFonts((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 7:  /* NewFontContents: no crossing [-42] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: diskfont.library.NewFontContents needs returns a pointer (struct FontContentsHeader *) described");
        r->d[0] = 0;
        return 1;
    case 8:  /* DisposeFontContents: no crossing [-48] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: diskfont.library.DisposeFontContents needs struct FontContentsHeader * described");
        r->d[0] = 0;
        return 1;
    case 9:  /* NewScaledDiskFont: no crossing [-54] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: diskfont.library.NewScaledDiskFont needs returns a pointer (struct DiskFont *) described");
        r->d[0] = 0;
        return 1;
    }
    return 1;   /* no safe generated crossing for this vector */
}
