/* GENERATED by graft/gen-struct-layouts - do not edit.
 *
 * The two layouts of every structure that crosses the 68k boundary: the
 * AmigaOS one the guest uses (big-endian, 32-bit pointers, packed to 2) and
 * the native aarch64 one. A field whose offsets differ cannot be copied, it
 * has to be converted, and these are the numbers that say where from and where
 * to. Both come from the AROS headers via clang, so they cannot drift from the
 * OS the way a hand-written table would.
 *
 * M68K_<Struct>_<field> is the guest offset; the native offset is offsetof()
 * on this side, which the compiler already knows - only the guest side needs
 * stating here.
 */

#ifndef EMU68K_LAYOUTS_H
#define EMU68K_LAYOUTS_H

/* One field of a structure, in both layouts at once. */
struct EmuField
{
    unsigned short g_off, n_off;   /* offset in the guest / native structure  */
    unsigned char  g_w, n_w;       /* width on each side (a guest LONG is 4,
                                    * a native IPTR is 8)                     */
    unsigned char  kind;
};


/* struct FileInfoBlock: 260 bytes on m68k (FileInfoBlock32), 264 native (FileInfoBlock32) */
#define M68K_FileInfoBlock_SIZEOF 260
#define M68K_FileInfoBlock_fib_DiskKey 0
#define M68K_FileInfoBlock_fib_DirEntryType 4   /* native @8 - CONVERT */
#define M68K_FileInfoBlock_fib_FileName 8   /* native @12 - CONVERT */
#define M68K_FileInfoBlock_fib_Protection 116   /* native @120 - CONVERT */
#define M68K_FileInfoBlock_fib_EntryType 120   /* native @124 - CONVERT */
#define M68K_FileInfoBlock_fib_Size 124   /* native @128 - CONVERT */
#define M68K_FileInfoBlock_fib_NumBlocks 128   /* native @132 - CONVERT */
#define M68K_FileInfoBlock_fib_Date 132   /* native @136 - CONVERT */
#define M68K_FileInfoBlock_ds_Days 132   /* native @136 - CONVERT */
#define M68K_FileInfoBlock_ds_Minute 136   /* native @140 - CONVERT */
#define M68K_FileInfoBlock_ds_Tick 140   /* native @144 - CONVERT */
#define M68K_FileInfoBlock_fib_Comment 144   /* native @148 - CONVERT */
#define M68K_FileInfoBlock_fib_OwnerUID 224   /* native @228 - CONVERT */
#define M68K_FileInfoBlock_fib_OwnerGID 226   /* native @230 - CONVERT */
#define M68K_FileInfoBlock_fib_Reserved 228   /* native @232 - CONVERT */

/* struct AnchorPath: 282 bytes on m68k (AnchorPath), 304 native (AnchorPath) */
#define M68K_AnchorPath_SIZEOF 282
#define M68K_AnchorPath_ap_Base 0
#define M68K_AnchorPath_ap_Last 4   /* native @8 - CONVERT */
#define M68K_AnchorPath_ap_BreakBits 8   /* native @16 - CONVERT */
#define M68K_AnchorPath_ap_FoundBreak 12   /* native @20 - CONVERT */
#define M68K_AnchorPath_ap_Flags 16   /* native @24 - CONVERT */
#define M68K_AnchorPath_ap_Reserved 17   /* native @25 - CONVERT */
#define M68K_AnchorPath_ap_Strlen 18   /* native @26 - CONVERT */
#define M68K_AnchorPath_ap_Info 20   /* native @32 - CONVERT */
#define M68K_AnchorPath_fib_DiskKey 20   /* native @32 - CONVERT */
#define M68K_AnchorPath_fib_DirEntryType 24   /* native @40 - CONVERT */
#define M68K_AnchorPath_fib_FileName 28   /* native @44 - CONVERT */
#define M68K_AnchorPath_fib_Protection 136   /* native @152 - CONVERT */
#define M68K_AnchorPath_fib_EntryType 140   /* native @156 - CONVERT */
#define M68K_AnchorPath_fib_Size 144   /* native @160 - CONVERT */
#define M68K_AnchorPath_fib_NumBlocks 148   /* native @164 - CONVERT */
#define M68K_AnchorPath_fib_Date 152   /* native @168 - CONVERT */
#define M68K_AnchorPath_ds_Days 152   /* native @168 - CONVERT */
#define M68K_AnchorPath_ds_Minute 156   /* native @172 - CONVERT */
#define M68K_AnchorPath_ds_Tick 160   /* native @176 - CONVERT */
#define M68K_AnchorPath_fib_Comment 164   /* native @180 - CONVERT */
#define M68K_AnchorPath_fib_OwnerUID 244   /* native @260 - CONVERT */
#define M68K_AnchorPath_fib_OwnerGID 246   /* native @262 - CONVERT */
#define M68K_AnchorPath_fib_Reserved 248   /* native @264 - CONVERT */
#define M68K_AnchorPath_ap_Buf 280   /* native @296 - CONVERT */

/* struct AChain: 274 bytes on m68k (AChain), 296 native (AChain) */
#define M68K_AChain_SIZEOF 274
#define M68K_AChain_an_Child 0
#define M68K_AChain_an_Parent 4   /* native @8 - CONVERT */
#define M68K_AChain_an_Lock 8   /* native @16 - CONVERT */
#define M68K_AChain_an_Info 12   /* native @24 - CONVERT */
#define M68K_AChain_fib_DiskKey 12   /* native @24 - CONVERT */
#define M68K_AChain_fib_DirEntryType 16   /* native @32 - CONVERT */
#define M68K_AChain_fib_FileName 20   /* native @36 - CONVERT */
#define M68K_AChain_fib_Protection 128   /* native @144 - CONVERT */
#define M68K_AChain_fib_EntryType 132   /* native @148 - CONVERT */
#define M68K_AChain_fib_Size 136   /* native @152 - CONVERT */
#define M68K_AChain_fib_NumBlocks 140   /* native @156 - CONVERT */
#define M68K_AChain_fib_Date 144   /* native @160 - CONVERT */
#define M68K_AChain_ds_Days 144   /* native @160 - CONVERT */
#define M68K_AChain_ds_Minute 148   /* native @164 - CONVERT */
#define M68K_AChain_ds_Tick 152   /* native @168 - CONVERT */
#define M68K_AChain_fib_Comment 156   /* native @172 - CONVERT */
#define M68K_AChain_fib_OwnerUID 236   /* native @252 - CONVERT */
#define M68K_AChain_fib_OwnerGID 238   /* native @254 - CONVERT */
#define M68K_AChain_fib_Reserved 240   /* native @256 - CONVERT */
#define M68K_AChain_an_Flags 272   /* native @288 - CONVERT */
#define M68K_AChain_an_String 273   /* native @289 - CONVERT */

/* struct DateStamp: 12 bytes on m68k (DateStamp), 12 native (DateStamp) */
#define M68K_DateStamp_SIZEOF 12
#define M68K_DateStamp_ds_Days 0
#define M68K_DateStamp_ds_Minute 4
#define M68K_DateStamp_ds_Tick 8

/* struct InfoData: 36 bytes on m68k (InfoData32), 48 native (InfoData32) */
#define M68K_InfoData_SIZEOF 36
#define M68K_InfoData_id_NumSoftErrors 0
#define M68K_InfoData_id_UnitNumber 4
#define M68K_InfoData_id_DiskState 8
#define M68K_InfoData_id_NumBlocks 12
#define M68K_InfoData_id_NumBlocksUsed 16
#define M68K_InfoData_id_BytesPerBlock 20
#define M68K_InfoData_id_DiskType 24
#define M68K_InfoData_id_VolumeNode 28   /* native @32 - CONVERT */
#define M68K_InfoData_id_InUse 32   /* native @40 - CONVERT */

/* struct TagItem: 8 bytes on m68k (TagItem), 16 native (TagItem) */
#define M68K_TagItem_SIZEOF 8
#define M68K_TagItem_ti_Tag 0
#define M68K_TagItem_ti_Data 4   /* native @8 - CONVERT */

/* struct Node: 14 bytes on m68k (Node), 32 native (Node) */
#define M68K_Node_SIZEOF 14
#define M68K_Node_ln_Succ 0
#define M68K_Node_ln_Pred 4   /* native @8 - CONVERT */
#define M68K_Node_ln_Type 8   /* native @16 - CONVERT */
#define M68K_Node_ln_Pri 9   /* native @17 - CONVERT */
#define M68K_Node_ln_Name 10   /* native @24 - CONVERT */

/* struct MinNode: 8 bytes on m68k (MinNode), 16 native (MinNode) */
#define M68K_MinNode_SIZEOF 8
#define M68K_MinNode_mln_Succ 0
#define M68K_MinNode_mln_Pred 4   /* native @8 - CONVERT */

/* struct List: 14 bytes on m68k (List), 32 native (List) */
#define M68K_List_SIZEOF 14
#define M68K_List_lh_Head 0
#define M68K_List_lh_Tail 4   /* native @8 - CONVERT */
#define M68K_List_lh_TailPred 8   /* native @16 - CONVERT */
#define M68K_List_lh_TailPred_ 8   /* native @16 - CONVERT */
#define M68K_List_lh_Type 12   /* native @24 - CONVERT */
#define M68K_List_l_pad 13   /* native @25 - CONVERT */

/* struct MinList: 12 bytes on m68k (MinList), 24 native (MinList) */
#define M68K_MinList_SIZEOF 12
#define M68K_MinList_mlh_Head 0
#define M68K_MinList_mlh_Tail 4   /* native @8 - CONVERT */
#define M68K_MinList_mlh_TailPred 8   /* native @16 - CONVERT */
#define M68K_MinList_mlh_TailPred_ 8   /* native @16 - CONVERT */

/* struct MsgPort: 42 bytes on m68k (MsgPort), 96 native (MsgPort) */
#define M68K_MsgPort_SIZEOF 42
#define M68K_MsgPort_mp_Node 0
#define M68K_MsgPort_ln_Succ 0
#define M68K_MsgPort_ln_Pred 4   /* native @8 - CONVERT */
#define M68K_MsgPort_ln_Type 8   /* native @16 - CONVERT */
#define M68K_MsgPort_ln_Pri 9   /* native @17 - CONVERT */
#define M68K_MsgPort_ln_Name 10   /* native @24 - CONVERT */
#define M68K_MsgPort_mp_Flags 14   /* native @32 - CONVERT */
#define M68K_MsgPort_mp_SigBit 15   /* native @33 - CONVERT */
#define M68K_MsgPort_mp_SigTask 16   /* native @40 - CONVERT */
#define M68K_MsgPort_mp_MsgList 20   /* native @48 - CONVERT */
#define M68K_MsgPort_lh_Head 20   /* native @48 - CONVERT */
#define M68K_MsgPort_lh_Tail 24   /* native @56 - CONVERT */
#define M68K_MsgPort_lh_TailPred 28   /* native @64 - CONVERT */
#define M68K_MsgPort_lh_TailPred_ 28   /* native @64 - CONVERT */
#define M68K_MsgPort_lh_Type 32   /* native @72 - CONVERT */
#define M68K_MsgPort_l_pad 33   /* native @73 - CONVERT */
#define M68K_MsgPort_mp_Pad 34   /* native @80 - CONVERT */
#define M68K_MsgPort_slock 34   /* native @80 - CONVERT */
#define M68K_MsgPort_block 34   /* native @80 - CONVERT */
#define M68K_MsgPort_lock 34   /* native @80 - CONVERT */
#define M68K_MsgPort_s_Owner 38   /* native @88 - CONVERT */

/* struct Message: 20 bytes on m68k (Message), 48 native (Message) */
#define M68K_Message_SIZEOF 20
#define M68K_Message_mn_Node 0
#define M68K_Message_ln_Succ 0
#define M68K_Message_ln_Pred 4   /* native @8 - CONVERT */
#define M68K_Message_ln_Type 8   /* native @16 - CONVERT */
#define M68K_Message_ln_Pri 9   /* native @17 - CONVERT */
#define M68K_Message_ln_Name 10   /* native @24 - CONVERT */
#define M68K_Message_mn_ReplyPort 14   /* native @32 - CONVERT */
#define M68K_Message_mn_Length 18   /* native @40 - CONVERT */

/* struct DiskObject: 78 bytes on m68k (DiskObject), 144 native (DiskObject) */
#define M68K_DiskObject_SIZEOF 78
#define M68K_DiskObject_do_Magic 0
#define M68K_DiskObject_do_Version 2
#define M68K_DiskObject_do_Gadget 4   /* native @8 - CONVERT */
#define M68K_DiskObject_NextGadget 4   /* native @8 - CONVERT */
#define M68K_DiskObject_LeftEdge 8   /* native @16 - CONVERT */
#define M68K_DiskObject_TopEdge 10   /* native @18 - CONVERT */
#define M68K_DiskObject_Width 12   /* native @20 - CONVERT */
#define M68K_DiskObject_Height 14   /* native @22 - CONVERT */
#define M68K_DiskObject_Flags 16   /* native @24 - CONVERT */
#define M68K_DiskObject_Activation 18   /* native @26 - CONVERT */
#define M68K_DiskObject_GadgetType 20   /* native @28 - CONVERT */
#define M68K_DiskObject_GadgetRender 22   /* native @32 - CONVERT */
#define M68K_DiskObject_SelectRender 26   /* native @40 - CONVERT */
#define M68K_DiskObject_GadgetText 30   /* native @48 - CONVERT */
#define M68K_DiskObject_MutualExclude 34   /* native @56 - CONVERT */
#define M68K_DiskObject_SpecialInfo 38   /* native @64 - CONVERT */
#define M68K_DiskObject_GadgetID 42   /* native @72 - CONVERT */
#define M68K_DiskObject_UserData 44   /* native @80 - CONVERT */
#define M68K_DiskObject_do_Type 48   /* native @88 - CONVERT */
#define M68K_DiskObject_do_DefaultTool 50   /* native @96 - CONVERT */
#define M68K_DiskObject_do_ToolTypes 54   /* native @104 - CONVERT */
#define M68K_DiskObject_do_CurrentX 58   /* native @112 - CONVERT */
#define M68K_DiskObject_do_CurrentY 62   /* native @116 - CONVERT */
#define M68K_DiskObject_do_DrawerData 66   /* native @120 - CONVERT */
#define M68K_DiskObject_do_ToolWindow 70   /* native @128 - CONVERT */
#define M68K_DiskObject_do_StackSize 74   /* native @136 - CONVERT */

/* struct ExAllData: 40 bytes on m68k (ExAllData32), 56 native (ExAllData32) */
#define M68K_ExAllData_SIZEOF 40
#define M68K_ExAllData_ed_Next 0
#define M68K_ExAllData_ed_Name 4   /* native @8 - CONVERT */
#define M68K_ExAllData_ed_Type 8   /* native @16 - CONVERT */
#define M68K_ExAllData_ed_Size 12   /* native @20 - CONVERT */
#define M68K_ExAllData_ed_Prot 16   /* native @24 - CONVERT */
#define M68K_ExAllData_ed_Days 20   /* native @28 - CONVERT */
#define M68K_ExAllData_ed_Mins 24   /* native @32 - CONVERT */
#define M68K_ExAllData_ed_Ticks 28   /* native @36 - CONVERT */
#define M68K_ExAllData_ed_Comment 32   /* native @40 - CONVERT */
#define M68K_ExAllData_ed_OwnerUID 36   /* native @48 - CONVERT */
#define M68K_ExAllData_ed_OwnerGID 38   /* native @50 - CONVERT */

/* struct Hook: 20 bytes on m68k (Hook), 40 native (Hook) */
#define M68K_Hook_SIZEOF 20
#define M68K_Hook_h_MinNode 0
#define M68K_Hook_mln_Succ 0
#define M68K_Hook_mln_Pred 4   /* native @8 - CONVERT */
#define M68K_Hook_h_Entry 8   /* native @16 - CONVERT */
#define M68K_Hook_h_SubEntry 12   /* native @24 - CONVERT */
#define M68K_Hook_h_Data 16   /* native @32 - CONVERT */

/* struct IClass: 60 bytes on m68k (IClass), 104 native (IClass) */
#define M68K_IClass_SIZEOF 60
#define M68K_IClass_cl_Dispatcher 0
#define M68K_IClass_h_MinNode 0
#define M68K_IClass_mln_Succ 0
#define M68K_IClass_mln_Pred 4   /* native @8 - CONVERT */
#define M68K_IClass_h_Entry 8   /* native @16 - CONVERT */
#define M68K_IClass_h_SubEntry 12   /* native @24 - CONVERT */
#define M68K_IClass_h_Data 16   /* native @32 - CONVERT */
#define M68K_IClass_cl_Reserved 20   /* native @40 - CONVERT */
#define M68K_IClass_cl_Super 24   /* native @48 - CONVERT */
#define M68K_IClass_cl_ID 28   /* native @56 - CONVERT */
#define M68K_IClass_cl_InstOffset 32   /* native @64 - CONVERT */
#define M68K_IClass_cl_InstSize 34   /* native @66 - CONVERT */
#define M68K_IClass_cl_UserData 36   /* native @72 - CONVERT */
#define M68K_IClass_cl_SubclassCount 40   /* native @80 - CONVERT */
#define M68K_IClass_cl_ObjectCount 44   /* native @84 - CONVERT */
#define M68K_IClass_cl_Flags 48   /* native @88 - CONVERT */
#define M68K_IClass_cl_ObjectSize 52   /* native @92 - CONVERT */
#define M68K_IClass_cl_MemoryPool 56   /* native @96 - CONVERT */

/* The conversion tables. Each row is one field: where it lives on
 * each side, how wide it is on each side, and what may be done to it.
 * A generic walker (emu68k_marshal.c) is all that is needed to convert
 * a whole structure, so no per-structure C is written by hand. */
#define EMU_F_SCALAR 0   /* byte-swapped, narrowed to the guest width */
#define EMU_F_BYTES  1   /* copied verbatim: no byte order to change  */

static const struct EmuField emu_fields_FileInfoBlock[] = {
    {    0,    0, 4, 8, EMU_F_SCALAR },   /* fib_DiskKey          IPTR */
    {    4,    8, 4, 4, EMU_F_SCALAR },   /* fib_DirEntryType     LONG */
    {    8,   12, 108, 108, EMU_F_BYTES },   /* fib_FileName         UBYTE[108] */
    {  116,  120, 4, 4, EMU_F_SCALAR },   /* fib_Protection       LONG */
    {  120,  124, 4, 4, EMU_F_SCALAR },   /* fib_EntryType        LONG */
    {  124,  128, 4, 4, EMU_F_SCALAR },   /* fib_Size             LONG */
    {  128,  132, 4, 4, EMU_F_SCALAR },   /* fib_NumBlocks        LONG */
    {  132,  136, 4, 4, EMU_F_SCALAR },   /* ds_Days              LONG */
    {  136,  140, 4, 4, EMU_F_SCALAR },   /* ds_Minute            LONG */
    {  140,  144, 4, 4, EMU_F_SCALAR },   /* ds_Tick              LONG */
    {  144,  148, 80, 80, EMU_F_BYTES },   /* fib_Comment          UBYTE[80] */
    {  224,  228, 2, 2, EMU_F_SCALAR },   /* fib_OwnerUID         UWORD */
    {  226,  230, 2, 2, EMU_F_SCALAR },   /* fib_OwnerGID         UWORD */
    {  228,  232, 32, 32, EMU_F_BYTES },   /* fib_Reserved         UBYTE[32] */
};
/* NOT converted, and deliberately not guessed at:
 *   fib_Date (struct DateStamp)
 */

static const struct EmuField emu_fields_AnchorPath[] = {
    {    8,   16, 4, 4, EMU_F_SCALAR },   /* ap_BreakBits         LONG */
    {   12,   20, 4, 4, EMU_F_SCALAR },   /* ap_FoundBreak        LONG */
    {   16,   24, 1, 1, EMU_F_SCALAR },   /* ap_Flags             BYTE */
    {   17,   25, 1, 1, EMU_F_SCALAR },   /* ap_Reserved          BYTE */
    {   18,   26, 2, 2, EMU_F_SCALAR },   /* ap_Strlen            WORD */
    {   20,   32, 4, 8, EMU_F_SCALAR },   /* fib_DiskKey          IPTR */
    {   24,   40, 4, 4, EMU_F_SCALAR },   /* fib_DirEntryType     LONG */
    {   28,   44, 108, 108, EMU_F_BYTES },   /* fib_FileName         UBYTE[108] */
    {  136,  152, 4, 4, EMU_F_SCALAR },   /* fib_Protection       LONG */
    {  140,  156, 4, 4, EMU_F_SCALAR },   /* fib_EntryType        LONG */
    {  144,  160, 4, 4, EMU_F_SCALAR },   /* fib_Size             LONG */
    {  148,  164, 4, 4, EMU_F_SCALAR },   /* fib_NumBlocks        LONG */
    {  152,  168, 4, 4, EMU_F_SCALAR },   /* ds_Days              LONG */
    {  156,  172, 4, 4, EMU_F_SCALAR },   /* ds_Minute            LONG */
    {  160,  176, 4, 4, EMU_F_SCALAR },   /* ds_Tick              LONG */
    {  164,  180, 80, 80, EMU_F_BYTES },   /* fib_Comment          UBYTE[80] */
    {  244,  260, 2, 2, EMU_F_SCALAR },   /* fib_OwnerUID         UWORD */
    {  246,  262, 2, 2, EMU_F_SCALAR },   /* fib_OwnerGID         UWORD */
    {  248,  264, 32, 32, EMU_F_BYTES },   /* fib_Reserved         UBYTE[32] */
    {  280,  296, 1, 1, EMU_F_BYTES },   /* ap_Buf               UBYTE[1] */
};
/* NOT converted, and deliberately not guessed at:
 *   ap_Base (struct AChain *)
 *   ap_Last (struct AChain *)
 *   ap_Info (struct FileInfoBlock32)
 *   fib_Date (struct DateStamp)
 */

static const struct EmuField emu_fields_AChain[] = {
    {   12,   24, 4, 8, EMU_F_SCALAR },   /* fib_DiskKey          IPTR */
    {   16,   32, 4, 4, EMU_F_SCALAR },   /* fib_DirEntryType     LONG */
    {   20,   36, 108, 108, EMU_F_BYTES },   /* fib_FileName         UBYTE[108] */
    {  128,  144, 4, 4, EMU_F_SCALAR },   /* fib_Protection       LONG */
    {  132,  148, 4, 4, EMU_F_SCALAR },   /* fib_EntryType        LONG */
    {  136,  152, 4, 4, EMU_F_SCALAR },   /* fib_Size             LONG */
    {  140,  156, 4, 4, EMU_F_SCALAR },   /* fib_NumBlocks        LONG */
    {  144,  160, 4, 4, EMU_F_SCALAR },   /* ds_Days              LONG */
    {  148,  164, 4, 4, EMU_F_SCALAR },   /* ds_Minute            LONG */
    {  152,  168, 4, 4, EMU_F_SCALAR },   /* ds_Tick              LONG */
    {  156,  172, 80, 80, EMU_F_BYTES },   /* fib_Comment          UBYTE[80] */
    {  236,  252, 2, 2, EMU_F_SCALAR },   /* fib_OwnerUID         UWORD */
    {  238,  254, 2, 2, EMU_F_SCALAR },   /* fib_OwnerGID         UWORD */
    {  240,  256, 32, 32, EMU_F_BYTES },   /* fib_Reserved         UBYTE[32] */
    {  272,  288, 1, 1, EMU_F_SCALAR },   /* an_Flags             BYTE */
    {  273,  289, 1, 1, EMU_F_BYTES },   /* an_String            UBYTE[1] */
};
/* NOT converted, and deliberately not guessed at:
 *   an_Child (struct AChain *)
 *   an_Parent (struct AChain *)
 *   an_Lock (BPTR)
 *   an_Info (struct FileInfoBlock32)
 *   fib_Date (struct DateStamp)
 */

static const struct EmuField emu_fields_DateStamp[] = {
    {    0,    0, 4, 4, EMU_F_SCALAR },   /* ds_Days              LONG */
    {    4,    4, 4, 4, EMU_F_SCALAR },   /* ds_Minute            LONG */
    {    8,    8, 4, 4, EMU_F_SCALAR },   /* ds_Tick              LONG */
};

static const struct EmuField emu_fields_InfoData[] = {
    {    0,    0, 4, 4, EMU_F_SCALAR },   /* id_NumSoftErrors     LONG */
    {    4,    4, 4, 4, EMU_F_SCALAR },   /* id_UnitNumber        LONG */
    {    8,    8, 4, 4, EMU_F_SCALAR },   /* id_DiskState         LONG */
    {   12,   12, 4, 4, EMU_F_SCALAR },   /* id_NumBlocks         LONG */
    {   16,   16, 4, 4, EMU_F_SCALAR },   /* id_NumBlocksUsed     LONG */
    {   20,   20, 4, 4, EMU_F_SCALAR },   /* id_BytesPerBlock     LONG */
    {   24,   24, 4, 4, EMU_F_SCALAR },   /* id_DiskType          LONG */
    {   32,   40, 4, 8, EMU_F_SCALAR },   /* id_InUse             IPTR */
};
/* NOT converted, and deliberately not guessed at:
 *   id_VolumeNode (BPTR)
 */

static const struct EmuField emu_fields_Node[] = {
    {    8,   16, 1, 1, EMU_F_SCALAR },   /* ln_Type              UBYTE */
    {    9,   17, 1, 1, EMU_F_SCALAR },   /* ln_Pri               BYTE */
};
/* NOT converted, and deliberately not guessed at:
 *   ln_Succ (struct Node *)
 *   ln_Pred (struct Node *)
 *   ln_Name (char *)
 */

static const struct EmuField emu_fields_List[] = {
    {   12,   24, 1, 1, EMU_F_SCALAR },   /* lh_Type              UBYTE */
    {   13,   25, 1, 1, EMU_F_SCALAR },   /* l_pad                UBYTE */
};
/* NOT converted, and deliberately not guessed at:
 *   lh_Head (struct Node *)
 *   lh_Tail (struct Node *)
 *   lh_TailPred (struct Node *)
 *   lh_TailPred_ (struct List *)
 */

static const struct EmuField emu_fields_MsgPort[] = {
    {    8,   16, 1, 1, EMU_F_SCALAR },   /* ln_Type              UBYTE */
    {    9,   17, 1, 1, EMU_F_SCALAR },   /* ln_Pri               BYTE */
    {   14,   32, 1, 1, EMU_F_SCALAR },   /* mp_Flags             UBYTE */
    {   15,   33, 1, 1, EMU_F_SCALAR },   /* mp_SigBit            UBYTE */
    {   32,   72, 1, 1, EMU_F_SCALAR },   /* lh_Type              UBYTE */
    {   33,   73, 1, 1, EMU_F_SCALAR },   /* l_pad                UBYTE */
};
/* NOT converted, and deliberately not guessed at:
 *   mp_Node (struct Node)
 *   ln_Succ (struct Node *)
 *   ln_Pred (struct Node *)
 *   ln_Name (char *)
 *   mp_SigTask (void *)
 *   mp_MsgList (struct List)
 *   lh_Head (struct Node *)
 *   lh_Tail (struct Node *)
 *   lh_TailPred (struct Node *)
 *   lh_TailPred_ (struct List *)
 *   mp_Pad (spinlock_t)
 *   slock (struct spinlock_t::(unnamed at /Users/jkn/aros-build/bin/darwin-aarch64/AROS/Developer/include/aros/types/spinlock_s.h:25:18))
 *   block (volatile unsigned char[4])
 *   lock (volatile unsigned int)
 *   s_Owner (void *)
 */

static const struct EmuField emu_fields_Message[] = {
    {    8,   16, 1, 1, EMU_F_SCALAR },   /* ln_Type              UBYTE */
    {    9,   17, 1, 1, EMU_F_SCALAR },   /* ln_Pri               BYTE */
    {   18,   40, 2, 2, EMU_F_SCALAR },   /* mn_Length            UWORD */
};
/* NOT converted, and deliberately not guessed at:
 *   mn_Node (struct Node)
 *   ln_Succ (struct Node *)
 *   ln_Pred (struct Node *)
 *   ln_Name (char *)
 *   mn_ReplyPort (struct MsgPort *)
 */

static const struct EmuField emu_fields_DiskObject[] = {
    {    0,    0, 2, 2, EMU_F_SCALAR },   /* do_Magic             UWORD */
    {    2,    2, 2, 2, EMU_F_SCALAR },   /* do_Version           UWORD */
    {    8,   16, 2, 2, EMU_F_SCALAR },   /* LeftEdge             WORD */
    {   10,   18, 2, 2, EMU_F_SCALAR },   /* TopEdge              WORD */
    {   12,   20, 2, 2, EMU_F_SCALAR },   /* Width                WORD */
    {   14,   22, 2, 2, EMU_F_SCALAR },   /* Height               WORD */
    {   16,   24, 2, 2, EMU_F_SCALAR },   /* Flags                UWORD */
    {   18,   26, 2, 2, EMU_F_SCALAR },   /* Activation           UWORD */
    {   20,   28, 2, 2, EMU_F_SCALAR },   /* GadgetType           UWORD */
    {   42,   72, 2, 2, EMU_F_SCALAR },   /* GadgetID             UWORD */
    {   48,   88, 1, 1, EMU_F_SCALAR },   /* do_Type              UBYTE */
    {   58,  112, 4, 4, EMU_F_SCALAR },   /* do_CurrentX          LONG */
    {   62,  116, 4, 4, EMU_F_SCALAR },   /* do_CurrentY          LONG */
    {   74,  136, 4, 4, EMU_F_SCALAR },   /* do_StackSize         LONG */
};
/* NOT converted, and deliberately not guessed at:
 *   do_Gadget (struct Gadget)
 *   NextGadget (struct Gadget *)
 *   GadgetRender (APTR)
 *   SelectRender (APTR)
 *   GadgetText (struct IntuiText *)
 *   MutualExclude (IPTR)
 *   SpecialInfo (APTR)
 *   UserData (APTR)
 *   do_DefaultTool (STRPTR)
 *   do_ToolTypes (STRPTR *)
 *   do_DrawerData (struct DrawerData *)
 *   do_ToolWindow (STRPTR)
 */

static const struct EmuField emu_fields_ExAllData[] = {
    {    8,   16, 4, 4, EMU_F_SCALAR },   /* ed_Type              LONG */
    {   12,   20, 4, 4, EMU_F_SCALAR },   /* ed_Size              ULONG */
    {   16,   24, 4, 4, EMU_F_SCALAR },   /* ed_Prot              ULONG */
    {   20,   28, 4, 4, EMU_F_SCALAR },   /* ed_Days              ULONG */
    {   24,   32, 4, 4, EMU_F_SCALAR },   /* ed_Mins              ULONG */
    {   28,   36, 4, 4, EMU_F_SCALAR },   /* ed_Ticks             ULONG */
    {   36,   48, 2, 2, EMU_F_SCALAR },   /* ed_OwnerUID          UWORD */
    {   38,   50, 2, 2, EMU_F_SCALAR },   /* ed_OwnerGID          UWORD */
};
/* NOT converted, and deliberately not guessed at:
 *   ed_Next (struct ExAllData32 *)
 *   ed_Name (UBYTE *)
 *   ed_Comment (UBYTE *)
 */

static const struct EmuField emu_fields_IClass[] = {
    {   20,   40, 4, 4, EMU_F_SCALAR },   /* cl_Reserved          ULONG */
    {   32,   64, 2, 2, EMU_F_SCALAR },   /* cl_InstOffset        UWORD */
    {   34,   66, 2, 2, EMU_F_SCALAR },   /* cl_InstSize          UWORD */
    {   40,   80, 4, 4, EMU_F_SCALAR },   /* cl_SubclassCount     ULONG */
    {   44,   84, 4, 4, EMU_F_SCALAR },   /* cl_ObjectCount       ULONG */
    {   48,   88, 4, 4, EMU_F_SCALAR },   /* cl_Flags             ULONG */
    {   52,   92, 4, 4, EMU_F_SCALAR },   /* cl_ObjectSize        ULONG */
};
/* NOT converted, and deliberately not guessed at:
 *   cl_Dispatcher (struct Hook)
 *   h_MinNode (struct MinNode)
 *   mln_Succ (struct MinNode *)
 *   mln_Pred (struct MinNode *)
 *   h_Entry (APTR)
 *   h_SubEntry (APTR)
 *   h_Data (APTR)
 *   cl_Super (struct IClass *)
 *   cl_ID (ClassID)
 *   cl_UserData (IPTR)
 *   cl_MemoryPool (APTR)
 */

#endif /* EMU68K_LAYOUTS_H */
