/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/commodities/commodities.conf - do not edit.
 *
 * Derived crossings for commodities.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/commodities.h>

#include "emu68k_gen.h"

int emu68k_gen_commodities(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *CxBase = base;
    (void)r; (void)guest0; (void)CxBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 32:  /* BrokerCommand(STRPTR name, ULONG command) -> ULONG  [-192] */
        r->d[0] = (ULONG)BrokerCommand((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (ULONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
