/* GENERATED by graft/gen-emu68k-bridge from rom/keymap/keymap.conf - do not edit.
 *
 * Tier 1 crossings for keymap.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/keymap.h>

#include "emu68k_gen.h"

int emu68k_gen_keymap(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *KeymapBase = base;
    (void)r; (void)guest0; (void)KeymapBase;

    switch (lvo)
    {
    }
    return 1;   /* not a tier-1 vector of this library */
}
