/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/icon/icon.conf - do not edit.
 *
 * Derived crossings for icon.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/icon.h>
#include <string.h>
#include <stdio.h>
#include <workbench/icon.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_icon_duplicate[] =
{
    { ICONDUPA_DuplicateDrawerData, EMU_TAG_U32, "ICONDUPA_DuplicateDrawerData", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_DuplicateImages, EMU_TAG_U32, "ICONDUPA_DuplicateImages", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_DuplicateImageData, EMU_TAG_U32, "ICONDUPA_DuplicateImageData", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_DuplicateDefaultTool, EMU_TAG_U32, "ICONDUPA_DuplicateDefaultTool", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_DuplicateToolTypes, EMU_TAG_U32, "ICONDUPA_DuplicateToolTypes", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_DuplicateToolWindow, EMU_TAG_U32, "ICONDUPA_DuplicateToolWindow", NULL, 0, 0, 0, 0, 0 },
    { ICONDUPA_ActivateImageData, EMU_TAG_U32, "ICONDUPA_ActivateImageData", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_icon_duplicate =
{
    emu_tagdesc_icon_duplicate, 7, "icon.duplicate"
};

static const struct EmuTagDesc emu_tagdesc_import_icon_GetIconRectangleA_tags[] =
{
    { ICONDRAWA_Borderless, EMU_TAG_U32, "ICONDRAWA_Borderless", NULL, 0, 0, 0, 0, 0 },
    { ICONDRAWA_Frameless, EMU_TAG_U32, "ICONDRAWA_Frameless", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_import_icon_GetIconRectangleA_tags =
{
    emu_tagdesc_import_icon_GetIconRectangleA_tags, 2, "import.icon.GetIconRectangleA.tags"
};

static const struct EmuTagDesc emu_tagdesc_import_icon_PutIconTagList_tags[] =
{
    { ICONPUTA_DropChunkyIconImage, EMU_TAG_U32, "ICONPUTA_DropChunkyIconImage", NULL, 0, 0, 0, 0, 0 },
    { ICONPUTA_DropNewIconToolTypes, EMU_TAG_U32, "ICONPUTA_DropNewIconToolTypes", NULL, 0, 0, 0, 0, 0 },
    { ICONPUTA_DropPlanarIconImage, EMU_TAG_U32, "ICONPUTA_DropPlanarIconImage", NULL, 0, 0, 0, 0, 0 },
    { ICONPUTA_OnlyUpdatePosition, EMU_TAG_U32, "ICONPUTA_OnlyUpdatePosition", NULL, 0, 0, 0, 0, 0 },
    { ICONPUTA_OptimizeImageSpace, EMU_TAG_U32, "ICONPUTA_OptimizeImageSpace", NULL, 0, 0, 0, 0, 0 },
    { ICONPUTA_PreserveOldIconImages, EMU_TAG_U32, "ICONPUTA_PreserveOldIconImages", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_import_icon_PutIconTagList_tags =
{
    emu_tagdesc_import_icon_PutIconTagList_tags, 6, "import.icon.PutIconTagList.tags"
};

static void emu_object_cleanup_DiskObject(APTR emu_base, APTR emu_object)
{
    struct Library *IconBase = emu_base;
    FreeDiskObject((struct DiskObject *)emu_object);
}

int emu68k_gen_icon(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *IconBase = base;
    (void)r; (void)guest0; (void)IconBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 9:  /* FreeFreeList: no crossing [-54] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.FreeFreeList needs struct FreeList * described");
        r->d[0] = 0;
        return 1;
    case 12:  /* AddFreeList: no crossing [-72] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.AddFreeList needs APTR mem, struct FreeList * described");
        r->d[0] = 0;
        return 1;
    case 13:  /* GetDiskObject(CONST_STRPTR name) -> struct DiskObject *  [-78] */
    {
        APTR emu_result = (APTR)GetDiskObject((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]));
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DiskObject,
                                             base, emu_object_cleanup_DiskObject,
                                             "DiskObject", M68K_DiskObject_SIZEOF,
                                             emu_fields_DiskObject, EMU_NFIELDS(emu_fields_DiskObject),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 14:  /* PutDiskObject(CONST_STRPTR name, struct DiskObject * icon) -> BOOL  [-84] */
    {
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_DiskObject, 1,
                                        "DiskObject", &emu_object_1, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)PutDiskObject((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]),
              (struct DiskObject *)emu_object_1);
            return 0;
    }
    case 15:  /* FreeDiskObject(struct DiskObject * diskobj) -> void  [-90] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_DiskObject, 1,
                                        "DiskObject", &emu_object_0, err, errlen) < 0)
            return 1;
            FreeDiskObject((struct DiskObject *)emu_object_0);
        emu68k_object_consume(guest0, r->a[0], EMU_OBJ_DiskObject);
            return 0;
    }
    case 16:  /* FindToolType: no crossing [-96] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.FindToolType needs returns a pointer (UBYTE *) described");
        r->d[0] = 0;
        return 1;
    case 17:  /* MatchToolValue(UBYTE * typeString, UBYTE * value) -> BOOL  [-102] */
        r->d[0] = (ULONG)MatchToolValue((UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (UBYTE *)EMU_GPTR(guest0, r->a[1]));
        return 0;
    case 18:  /* BumpRevision: no crossing [-108] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.BumpRevision needs returns a pointer (UBYTE *) described");
        r->d[0] = 0;
        return 1;
    case 20:  /* GetDefDiskObject(LONG type) -> struct DiskObject *  [-120] */
    {
        APTR emu_result = (APTR)GetDefDiskObject((LONG)r->d[0]);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DiskObject,
                                             base, emu_object_cleanup_DiskObject,
                                             "DiskObject", M68K_DiskObject_SIZEOF,
                                             emu_fields_DiskObject, EMU_NFIELDS(emu_fields_DiskObject),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 21:  /* PutDefDiskObject(struct DiskObject * icon) -> BOOL  [-126] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_DiskObject, 1,
                                        "DiskObject", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)PutDefDiskObject((struct DiskObject *)emu_object_0);
            return 0;
    }
    case 22:  /* GetDiskObjectNew(CONST_STRPTR name) -> struct DiskObject *  [-132] */
    {
        APTR emu_result = (APTR)GetDiskObjectNew((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]));
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DiskObject,
                                             base, emu_object_cleanup_DiskObject,
                                             "DiskObject", M68K_DiskObject_SIZEOF,
                                             emu_fields_DiskObject, EMU_NFIELDS(emu_fields_DiskObject),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 23:  /* DeleteDiskObject(UBYTE * name) -> BOOL  [-138] */
        r->d[0] = (ULONG)DeleteDiskObject((UBYTE *)EMU_GPTR(guest0, r->a[0]));
        return 0;
    case 25:  /* DupDiskObjectA(struct DiskObject * icon, struct TagItem * tags) -> struct DiskObject *  [-150] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_DiskObject, 0,
                                        "DiskObject", &emu_object_0, err, errlen) < 0)
            return 1;
        struct TagItem emu_tags_1[9];
        if (emu68k_tags_to_native(guest0, r->a[1], &emu_tagdomain_icon_duplicate, emu_tags_1, 9, NULL, 0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)DupDiskObjectA((struct DiskObject *)emu_object_0,
              (struct TagItem *)(r->a[1] ? emu_tags_1 : NULL));
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DiskObject,
                                             base, emu_object_cleanup_DiskObject,
                                             "DiskObject", M68K_DiskObject_SIZEOF,
                                             emu_fields_DiskObject, EMU_NFIELDS(emu_fields_DiskObject),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 26:  /* IconControlA: no crossing [-156] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.IconControlA needs struct DiskObject *, struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 27:  /* DrawIconStateA: no crossing [-162] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.DrawIconStateA needs struct DiskObject *, struct RastPort *, struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 28:  /* GetIconRectangleA(struct RastPort * rp, struct DiskObject * icon, STRPTR label, struct Rectangle * rectangle, struct TagItem * tags) -> BOOL  [-168] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_DiskObject, 1,
                                        "DiskObject", &emu_object_1, err, errlen) < 0)
            return 1;
        struct Rectangle emu_struct_3;
        if (!r->a[3])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: GetIconRectangleA.rectangle requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[3], M68K_Rectangle_SIZEOF,
                                         "GetIconRectangleA.rectangle", err, errlen) < 0)
            return 1;
        memset(&emu_struct_3, 0, sizeof(emu_struct_3));
        emu68k_from_guest_sized(guest0, r->a[3], &emu_struct_3,
                             emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
        struct TagItem emu_tags_4[9];
        if (emu68k_tags_to_native(guest0, r->a[4], &emu_tagdomain_import_icon_GetIconRectangleA_tags, emu_tags_4, 9, NULL, 0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)GetIconRectangleA((struct RastPort *)emu_object_0,
              (struct DiskObject *)emu_object_1,
              (STRPTR)EMU_GPTR(guest0, r->a[2]),
              (struct Rectangle *)&emu_struct_3,
              (struct TagItem *)(r->a[4] ? emu_tags_4 : NULL));
        emu68k_to_guest_sized(guest0, r->a[3], &emu_struct_3,
                           emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
            return 0;
    }
    case 29:  /* NewDiskObject(ULONG type) -> struct DiskObject *  [-174] */
    {
        APTR emu_result = (APTR)NewDiskObject((ULONG)r->d[0]);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DiskObject,
                                             base, emu_object_cleanup_DiskObject,
                                             "DiskObject", M68K_DiskObject_SIZEOF,
                                             emu_fields_DiskObject, EMU_NFIELDS(emu_fields_DiskObject),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 30:  /* GetIconTagList: no crossing [-180] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.GetIconTagList needs returns a pointer (struct DiskObject *) described");
        r->d[0] = 0;
        return 1;
    case 31:  /* PutIconTagList(CONST_STRPTR name, struct DiskObject * icon, struct TagItem * tags) -> BOOL  [-186] */
    {
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_DiskObject, 1,
                                        "DiskObject", &emu_object_1, err, errlen) < 0)
            return 1;
        struct TagItem emu_tags_2[11];
        if (emu68k_tags_to_native(guest0, r->a[2], &emu_tagdomain_import_icon_PutIconTagList_tags, emu_tags_2, 11, NULL, 0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)PutIconTagList((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]),
              (struct DiskObject *)emu_object_1,
              (struct TagItem *)(r->a[2] ? emu_tags_2 : NULL));
            return 0;
    }
    case 32:  /* LayoutIconA: no crossing [-192] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.LayoutIconA needs struct DiskObject *, struct Screen *, struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 33:  /* ChangeToSelectedIconColor: no crossing [-198] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: icon.library.ChangeToSelectedIconColor needs struct ColorRegister * described");
        r->d[0] = 0;
        return 1;
    }
    return 1;   /* no safe generated crossing for this vector */
}
