/* GENERATED by graft/gen-emu68k-bridge - do not edit.
 *
 * The generated half of the 68k -> native library bridge. One entry point per
 * library; each returns 0 when it served the call and 1 when the vector is not
 * one it covers, so the hand-written bridge stays in charge of everything that
 * needs judgement.
 */

#ifndef EMU68K_GEN_H
#define EMU68K_GEN_H

#include <exec/types.h>

/* The leading, stable part of the engine's 68k register file. The engine owns
 * the full struct; only these two arrays are contractual here. */
struct Emu68kRegs
{
    ULONG d[8];
    ULONG a[8];
};

/* A guest pointer becomes a host pointer by adding the guest base. Only memory
 * inside the guest arena may be handed to a native call this way. */
#define EMU_GPTR(g0, a)  ((APTR)((a) ? (UBYTE *)(g0) + (ULONG)(a) : NULL))

int emu68k_gen_exec(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_dos(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_utility(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_intuition(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_graphics(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_layers(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_gadtools(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_asl(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_icon(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_iffparse(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_commodities(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_diskfont(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_locale(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_keymap(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_datatypes(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_expansion(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_cybergraphics(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_mathffp(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_mathieeesingbas(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
int emu68k_gen_mathieeedoubbas(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base);
#endif /* EMU68K_GEN_H */
