/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/icon/icon.conf - do not edit.
 *
 * Derived crossings for icon.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/icon.h>

#include "emu68k_gen.h"

int emu68k_gen_icon(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *IconBase = base;
    (void)r; (void)guest0; (void)IconBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 17:  /* MatchToolValue(UBYTE * typeString, UBYTE * value) -> BOOL  [-102] */
        r->d[0] = (ULONG)MatchToolValue((UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (UBYTE *)EMU_GPTR(guest0, r->a[1]));
        return 0;
    case 23:  /* DeleteDiskObject(UBYTE * name) -> BOOL  [-138] */
        r->d[0] = (ULONG)DeleteDiskObject((UBYTE *)EMU_GPTR(guest0, r->a[0]));
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
