/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathieeedoubbas/mathieeedoubbas.conf - do not edit.
 *
 * Derived crossings for mathieeedoubbas.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/mathieeedoubbas.h>

#include "emu68k_gen.h"

int emu68k_gen_mathieeedoubbas(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *MathIeeeDoubBasBase = base;
    (void)r; (void)guest0; (void)MathIeeeDoubBasBase; (void)err; (void)errlen;

    switch (lvo)
    {
    }
    return 1;   /* no safe generated crossing for this vector */
}
