/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/cgfx/cybergraphics.conf - do not edit.
 *
 * Derived crossings for cybergraphics.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/cybergraphics.h>
#include <string.h>
#include <stdio.h>
#include <cybergraphx/cybergraphics.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_cybergraphics_best_mode[] =
{
    { CYBRBIDTG_Depth, EMU_TAG_U32, "CYBRBIDTG_Depth", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_NominalWidth, EMU_TAG_U32, "CYBRBIDTG_NominalWidth", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_NominalHeight, EMU_TAG_U32, "CYBRBIDTG_NominalHeight", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_MonitorID, EMU_TAG_U32, "CYBRBIDTG_MonitorID", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_BoardName, EMU_TAG_CSTR, "CYBRBIDTG_BoardName", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_cybergraphics_best_mode =
{
    emu_tagdesc_cybergraphics_best_mode, 5, "cybergraphics.best_mode"
};

static const struct EmuTagDesc emu_tagdesc_cybergraphics_video_control[] =
{
    { SETVC_DPMSLevel, EMU_TAG_U32, "SETVC_DPMSLevel", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_cybergraphics_video_control =
{
    emu_tagdesc_cybergraphics_video_control, 1, "cybergraphics.video_control"
};

static const struct EmuTagDesc emu_tagdesc_cybergraphics_process_pixels[] =
{
    { PPAOPTAG_GRADIENTTYPE, EMU_TAG_U32, "PPAOPTAG_GRADIENTTYPE", NULL, 0, 0, 0, 0, 0 },
    { PPAOPTAG_GRADCOLOR1, EMU_TAG_U32, "PPAOPTAG_GRADCOLOR1", NULL, 0, 0, 0, 0, 0 },
    { PPAOPTAG_GRADCOLOR2, EMU_TAG_U32, "PPAOPTAG_GRADCOLOR2", NULL, 0, 0, 0, 0, 0 },
    { PPAOPTAG_GRADFULLSCALE, EMU_TAG_U32, "PPAOPTAG_GRADFULLSCALE", NULL, 0, 0, 0, 0, 0 },
    { PPAOPTAG_GRADOFFSET, EMU_TAG_U32, "PPAOPTAG_GRADOFFSET", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_cybergraphics_process_pixels =
{
    emu_tagdesc_cybergraphics_process_pixels, 5, "cybergraphics.process_pixels"
};

int emu68k_gen_cybergraphics(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *CyberGfxBase = base;
    (void)r; (void)guest0; (void)CyberGfxBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 9:  /* IsCyberModeID(ULONG modeID) -> BOOL  [-54] */
        r->d[0] = (ULONG)IsCyberModeID((ULONG)r->d[0]);
        return 0;
    case 10:  /* BestCModeIDTagList(struct TagItem * tags) -> ULONG  [-60] */
    {
        struct TagItem emu_tags_0[17];
        if (emu68k_tags_to_native(guest0, r->a[0], &emu_tagdomain_cybergraphics_best_mode, emu_tags_0, 17, NULL, 0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)BestCModeIDTagList((struct TagItem *)(r->a[0] ? emu_tags_0 : NULL));
            return 0;
    }
    case 12:  /* AllocCModeListTagList: explicit reviewed refusal [-72] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.AllocCModeListTagList refused: returns a guest-traversed List whose dynamically allocated CyberModeNode chain and embedded mode names require linked facades");
        r->d[0] = 0;
        return 1;
    case 13:  /* FreeCModeList: explicit reviewed refusal [-78] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.FreeCModeList refused: paired handwritten release for the guest-linked CyberModeNode facade list");
        r->d[0] = 0;
        return 1;
    case 15:  /* ScalePixelArray(APTR srcRect, UWORD SrcW, UWORD SrcH, UWORD SrcMod, struct RastPort * RastPort, UWORD DestX, UWORD DestY, UWORD DestW, UWORD DestH, UBYTE SrcFormat) -> LONG  [-90] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[2];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "ScalePixelArray.srcRect extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (ULONG)r->d[1];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "ScalePixelArray.srcRect extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "ScalePixelArray.srcRect requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "ScalePixelArray.srcRect", err, errlen) < 0)
            return 1;
        APTR emu_object_4;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_4, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ScalePixelArray((APTR)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (struct RastPort *)emu_object_4,
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5],
              (UWORD)r->d[6],
              (UBYTE)r->d[7]);
            return 0;
    }
    case 16:  /* GetCyberMapAttr(struct BitMap * bitMap, IPTR attribute) -> IPTR  [-96] */
    {
        struct BitMap emu_struct_0;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: GetCyberMapAttr.bitMap requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[0], M68K_BitMap_SIZEOF,
                                         "GetCyberMapAttr.bitMap", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->a[0], &emu_struct_0,
                             emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            r->d[0] = (ULONG)GetCyberMapAttr((struct BitMap *)&emu_struct_0,
              (IPTR)(LONG)r->d[0]);   /* narrowed: an integer, never an address */
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            return 0;
    }
    case 17:  /* GetCyberIDAttr(ULONG attribute, ULONG DisplayModeID) -> ULONG  [-102] */
        r->d[0] = (ULONG)GetCyberIDAttr((ULONG)r->d[0],
              (ULONG)r->d[1]);
        return 0;
    case 18:  /* ReadRGBPixel(struct RastPort * rp, UWORD x, UWORD y) -> ULONG  [-108] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ReadRGBPixel((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1]);
            return 0;
    }
    case 19:  /* WriteRGBPixel(struct RastPort * rp, UWORD x, UWORD y, ULONG pixel) -> LONG  [-114] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)WriteRGBPixel((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (ULONG)r->d[2]);
            return 0;
    }
    case 20:  /* ReadPixelArray(APTR dst, UWORD destx, UWORD desty, UWORD dstmod, struct RastPort * rp, UWORD srcx, UWORD srcy, UWORD width, UWORD height, UBYTE dstformat) -> ULONG  [-120] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[2];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "ReadPixelArray.dst extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (UQUAD)(ULONG)r->d[1] + (UQUAD)(ULONG)r->d[6];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "ReadPixelArray.dst extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "ReadPixelArray.dst requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "ReadPixelArray.dst", err, errlen) < 0)
            return 1;
        APTR emu_object_4;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_4, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ReadPixelArray((APTR)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (struct RastPort *)emu_object_4,
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5],
              (UWORD)r->d[6],
              (UBYTE)r->d[7]);
            return 0;
    }
    case 21:  /* WritePixelArray(APTR src, UWORD srcx, UWORD srcy, UWORD srcmod, struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height, UBYTE srcformat) -> ULONG  [-126] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[2];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArray.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (UQUAD)(ULONG)r->d[1] + (UQUAD)(ULONG)r->d[6];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArray.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArray.src requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "WritePixelArray.src", err, errlen) < 0)
            return 1;
        APTR emu_object_4;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_4, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)WritePixelArray((APTR)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (struct RastPort *)emu_object_4,
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5],
              (UWORD)r->d[6],
              (UBYTE)r->d[7]);
            return 0;
    }
    case 22:  /* MovePixelArray(UWORD SrcX, UWORD SrcY, struct RastPort * RastPort, UWORD DstX, UWORD DstY, UWORD SizeX, UWORD SizeY) -> ULONG  [-132] */
    {
        APTR emu_object_2;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_2, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)MovePixelArray((UWORD)r->d[0],
              (UWORD)r->d[1],
              (struct RastPort *)emu_object_2,
              (UWORD)r->d[2],
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5]);
            return 0;
    }
    case 24:  /* InvertPixelArray(struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height) -> ULONG  [-144] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)InvertPixelArray((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (UWORD)r->d[3]);
            return 0;
    }
    case 25:  /* FillPixelArray(struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height, ULONG pixel) -> ULONG  [-150] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)FillPixelArray((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (UWORD)r->d[3],
              (ULONG)r->d[4]);
            return 0;
    }
    case 26:  /* DoCDrawMethodTagList: explicit reviewed refusal [-156] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.DoCDrawMethodTagList refused: invokes a guest hook from native code with native RastPort and CDrawMsg pointers requiring callback-specific facades");
        r->d[0] = 0;
        return 1;
    case 27:  /* CVideoCtrlTagList(struct ViewPort * vp, struct TagItem * tags) -> void  [-162] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_ViewPort, 0,
                                        "ViewPort", &emu_object_0, err, errlen) < 0)
            return 1;
        struct TagItem emu_tags_1[5];
        if (emu68k_tags_to_native(guest0, r->a[1], &emu_tagdomain_cybergraphics_video_control, emu_tags_1, 5, NULL, 0, err, errlen) < 0)
            return 1;
            CVideoCtrlTagList((struct ViewPort *)emu_object_0,
              (struct TagItem *)(r->a[1] ? emu_tags_1 : NULL));
            return 0;
    }
    case 28:  /* LockBitMapTagList: explicit reviewed refusal [-168] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.LockBitMapTagList refused: exposes a native framebuffer base address through LBMI_BASEADDRESS, which is not addressable by the 32-bit guest");
        r->d[0] = 0;
        return 1;
    case 29:  /* UnLockBitMap: explicit reviewed refusal [-174] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.UnLockBitMap refused: paired release for the refused native framebuffer lock handle");
        r->d[0] = 0;
        return 1;
    case 30:  /* UnLockBitMapTagList: explicit reviewed refusal [-180] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: cybergraphics.library.UnLockBitMapTagList refused: paired release for the refused native framebuffer lock handle");
        r->d[0] = 0;
        return 1;
    case 31:  /* ExtractColor(struct RastPort * RastPort, struct BitMap * SingleMap, ULONG Colour, ULONG sX, ULONG sY, ULONG Width, ULONG Height) -> ULONG  [-186] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
        struct BitMap emu_struct_1;
        if (!r->a[1])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: ExtractColor.SingleMap requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[1], M68K_BitMap_SIZEOF,
                                         "ExtractColor.SingleMap", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            r->d[0] = (ULONG)ExtractColor((struct RastPort *)emu_object_0,
              (struct BitMap *)&emu_struct_1,
              (ULONG)r->d[0],
              (ULONG)r->d[1],
              (ULONG)r->d[2],
              (ULONG)r->d[3],
              (ULONG)r->d[4]);
        emu68k_to_guest_sized(guest0, r->a[1], &emu_struct_1,
                           emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            return 0;
    }
    case 33:  /* WriteLUTPixelArray(APTR srcRect, UWORD SrcX, UWORD SrcY, UWORD SrcMod, struct RastPort * rp, APTR CTable, UWORD DestX, UWORD DestY, UWORD SizeX, UWORD SizeY, UBYTE CTabFormat) -> LONG  [-198] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[2];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "WriteLUTPixelArray.srcRect extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (UQUAD)(ULONG)r->d[1] + (UQUAD)(ULONG)r->d[6];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "WriteLUTPixelArray.srcRect extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "WriteLUTPixelArray.srcRect requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "WriteLUTPixelArray.srcRect", err, errlen) < 0)
            return 1;
        APTR emu_object_4;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_4, err, errlen) < 0)
            return 1;
        ULONG emu_array_count_5 = 256;
        ULONG emu_array_size_5 = sizeof(ULONG) * 256;
        APTR emu_array_scratch_5 = NULL;
        if (!r->a[2])
        {
            if (err && errlen)
                snprintf(err, errlen, "WriteLUTPixelArray.CTable requires a non-NULL array");
            return 1;
        }
        if (r->a[2])
        {
            emu_array_scratch_5 = emu68k_scratch_alloc(
                emu_array_size_5, err, errlen);
            if (!emu_array_scratch_5)
            {
                return 1;
            }
            if (emu68k_require_guest_range(r->a[2], emu_array_count_5 * 4,
                    "WriteLUTPixelArray.CTable", err, errlen) < 0)
            {
                emu68k_scratch_free(emu_array_scratch_5, emu_array_size_5);
                return 1;
            }
            for (ULONG emu_array_i_5 = 0; emu_array_i_5 < emu_array_count_5; emu_array_i_5++)
                ((ULONG *)emu_array_scratch_5)[emu_array_i_5] = (ULONG)
                    emu68k_scalar_from_guest(guest0, r->a[2] + emu_array_i_5 * 4, 4);
        }
            r->d[0] = (ULONG)WriteLUTPixelArray((APTR)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (struct RastPort *)emu_object_4,
              (APTR)emu_array_scratch_5,
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5],
              (UWORD)r->d[6],
              (UBYTE)r->d[7]);
        if (emu_array_scratch_5)
            emu68k_scratch_free(emu_array_scratch_5, emu_array_size_5);
            return 0;
    }
    case 36:  /* WritePixelArrayAlpha(APTR src, UWORD srcx, UWORD srcy, UWORD srcmod, struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height, ULONG globalalpha) -> ULONG  [-216] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[2];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArrayAlpha.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (UQUAD)(ULONG)r->d[1] + (UQUAD)(ULONG)r->d[6];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArrayAlpha.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "WritePixelArrayAlpha.src requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "WritePixelArrayAlpha.src", err, errlen) < 0)
            return 1;
        APTR emu_object_4;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_4, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)WritePixelArrayAlpha((APTR)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (struct RastPort *)emu_object_4,
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5],
              (UWORD)r->d[6],
              (ULONG)r->d[7]);
            return 0;
    }
    case 37:  /* BltTemplateAlpha(APTR src, LONG srcx, LONG srcmod, struct RastPort * rp, LONG destx, LONG desty, LONG width, LONG height) -> void  [-222] */
    {
        UQUAD emu_buffer_size_0 = 1;
        UQUAD emu_buffer_factor_0_0 = (ULONG)r->d[1];
        if (emu_buffer_factor_0_0 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_0)
        {
            if (err && errlen)
                snprintf(err, errlen, "BltTemplateAlpha.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_0;
        UQUAD emu_buffer_factor_0_1 = (ULONG)r->d[5];
        if (emu_buffer_factor_0_1 && emu_buffer_size_0 >
            0xffffffffUL / emu_buffer_factor_0_1)
        {
            if (err && errlen)
                snprintf(err, errlen, "BltTemplateAlpha.src extent overflows guest memory");
            return 1;
        }
        emu_buffer_size_0 *= emu_buffer_factor_0_1;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "BltTemplateAlpha.src requires a non-NULL buffer");
            return 1;
        }
        if (r->a[0] && emu68k_require_guest_range(r->a[0],
                (ULONG)emu_buffer_size_0, "BltTemplateAlpha.src", err, errlen) < 0)
            return 1;
        APTR emu_object_3;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_3, err, errlen) < 0)
            return 1;
            BltTemplateAlpha((APTR)EMU_GPTR(guest0, r->a[0]),
              (LONG)r->d[0],
              (LONG)r->d[1],
              (struct RastPort *)emu_object_3,
              (LONG)r->d[2],
              (LONG)r->d[3],
              (LONG)r->d[4],
              (LONG)r->d[5]);
            return 0;
    }
    case 38:  /* ProcessPixelArray(struct RastPort * rp, ULONG destX, ULONG destY, ULONG sizeX, ULONG sizeY, ULONG operation, LONG value, struct TagItem * taglist) -> VOID  [-228] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 0,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
        struct TagItem emu_tags_7[9];
        if (emu68k_tags_to_native(guest0, r->a[2], &emu_tagdomain_cybergraphics_process_pixels, emu_tags_7, 9, NULL, 0, err, errlen) < 0)
            return 1;
            ProcessPixelArray((struct RastPort *)emu_object_0,
              (ULONG)r->d[0],
              (ULONG)r->d[1],
              (ULONG)r->d[2],
              (ULONG)r->d[3],
              (ULONG)r->d[4],
              (LONG)r->d[5],
              (struct TagItem *)(r->a[2] ? emu_tags_7 : NULL));
            return 0;
    }
    }
    return 1;   /* no safe generated crossing for this vector */
}
