/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/cgfx/cybergraphics.conf - do not edit.
 *
 * Derived crossings for cybergraphics.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/cybergraphics.h>
#include <string.h>
#include <cybergraphx/cybergraphics.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_cybergraphics_best_mode[] =
{
    { CYBRBIDTG_Depth, EMU_TAG_U32, "CYBRBIDTG_Depth", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_NominalWidth, EMU_TAG_U32, "CYBRBIDTG_NominalWidth", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_NominalHeight, EMU_TAG_U32, "CYBRBIDTG_NominalHeight", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_MonitorID, EMU_TAG_U32, "CYBRBIDTG_MonitorID", NULL, 0, 0, 0, 0, 0 },
    { CYBRBIDTG_BoardName, EMU_TAG_CSTR, "CYBRBIDTG_BoardName", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_cybergraphics_best_mode =
{
    emu_tagdesc_cybergraphics_best_mode, 5, "cybergraphics.best_mode"
};

int emu68k_gen_cybergraphics(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *CyberGfxBase = base;
    (void)r; (void)guest0; (void)CyberGfxBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 9:  /* IsCyberModeID(ULONG modeID) -> BOOL  [-54] */
        r->d[0] = (ULONG)IsCyberModeID((ULONG)r->d[0]);
        return 0;
    case 10:  /* BestCModeIDTagList(struct TagItem * tags) -> ULONG  [-60] */
    {
        struct TagItem emu_tags_0[17];
        if (emu68k_tags_to_native(guest0, r->a[0], &emu_tagdomain_cybergraphics_best_mode, emu_tags_0, 17, NULL, 0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)BestCModeIDTagList((struct TagItem *)(r->a[0] ? emu_tags_0 : NULL));
            return 0;
    }
    case 13:  /* FreeCModeList(struct List * modeList) -> void  [-78] */
    {
        struct List emu_struct_0;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: FreeCModeList.modeList requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[0], M68K_List_SIZEOF,
                                         "FreeCModeList.modeList", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->a[0], &emu_struct_0,
                             emu_fields_List, EMU_NFIELDS(emu_fields_List), M68K_List_SIZEOF);
            FreeCModeList((struct List *)&emu_struct_0);
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_List, EMU_NFIELDS(emu_fields_List), M68K_List_SIZEOF);
            return 0;
    }
    case 16:  /* GetCyberMapAttr(struct BitMap * bitMap, IPTR attribute) -> IPTR  [-96] */
    {
        struct BitMap emu_struct_0;
        if (!r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: GetCyberMapAttr.bitMap requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[0], M68K_BitMap_SIZEOF,
                                         "GetCyberMapAttr.bitMap", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->a[0], &emu_struct_0,
                             emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            r->d[0] = (ULONG)GetCyberMapAttr((struct BitMap *)&emu_struct_0,
              (IPTR)(LONG)r->d[0]);   /* narrowed: an integer, never an address */
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            return 0;
    }
    case 17:  /* GetCyberIDAttr(ULONG attribute, ULONG DisplayModeID) -> ULONG  [-102] */
        r->d[0] = (ULONG)GetCyberIDAttr((ULONG)r->d[0],
              (ULONG)r->d[1]);
        return 0;
    case 18:  /* ReadRGBPixel(struct RastPort * rp, UWORD x, UWORD y) -> ULONG  [-108] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ReadRGBPixel((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1]);
            return 0;
    }
    case 19:  /* WriteRGBPixel(struct RastPort * rp, UWORD x, UWORD y, ULONG pixel) -> LONG  [-114] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)WriteRGBPixel((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (ULONG)r->d[2]);
            return 0;
    }
    case 22:  /* MovePixelArray(UWORD SrcX, UWORD SrcY, struct RastPort * RastPort, UWORD DstX, UWORD DstY, UWORD SizeX, UWORD SizeY) -> ULONG  [-132] */
    {
        APTR emu_object_2;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_2, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)MovePixelArray((UWORD)r->d[0],
              (UWORD)r->d[1],
              (struct RastPort *)emu_object_2,
              (UWORD)r->d[2],
              (UWORD)r->d[3],
              (UWORD)r->d[4],
              (UWORD)r->d[5]);
            return 0;
    }
    case 24:  /* InvertPixelArray(struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height) -> ULONG  [-144] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)InvertPixelArray((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (UWORD)r->d[3]);
            return 0;
    }
    case 25:  /* FillPixelArray(struct RastPort * rp, UWORD destx, UWORD desty, UWORD width, UWORD height, ULONG pixel) -> ULONG  [-150] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)FillPixelArray((struct RastPort *)emu_object_0,
              (UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2],
              (UWORD)r->d[3],
              (ULONG)r->d[4]);
            return 0;
    }
    case 31:  /* ExtractColor(struct RastPort * RastPort, struct BitMap * SingleMap, ULONG Colour, ULONG sX, ULONG sY, ULONG Width, ULONG Height) -> ULONG  [-186] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_RastPort, 1,
                                        "RastPort", &emu_object_0, err, errlen) < 0)
            return 1;
        struct BitMap emu_struct_1;
        if (!r->a[1])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: ExtractColor.SingleMap requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->a[1], M68K_BitMap_SIZEOF,
                                         "ExtractColor.SingleMap", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            r->d[0] = (ULONG)ExtractColor((struct RastPort *)emu_object_0,
              (struct BitMap *)&emu_struct_1,
              (ULONG)r->d[0],
              (ULONG)r->d[1],
              (ULONG)r->d[2],
              (ULONG)r->d[3],
              (ULONG)r->d[4]);
        emu68k_to_guest_sized(guest0, r->a[1], &emu_struct_1,
                           emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            return 0;
    }
    }
    return 1;   /* no safe generated crossing for this vector */
}
