/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathtrans/mathtrans.conf - do not edit.
 *
 * Derived crossings for mathtrans.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/mathtrans.h>

#include "emu68k_gen.h"

int emu68k_gen_mathtrans(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *MathTransBase = base;
    (void)r; (void)guest0; (void)MathTransBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 5:  /* SPAtan(LONG fnum1) -> LONG  [-30] */
        r->d[0] = (ULONG)SPAtan((LONG)r->d[0]);
        return 0;
    case 6:  /* SPSin(LONG fnum1) -> LONG  [-36] */
        r->d[0] = (ULONG)SPSin((LONG)r->d[0]);
        return 0;
    case 7:  /* SPCos(LONG fnum1) -> LONG  [-42] */
        r->d[0] = (ULONG)SPCos((LONG)r->d[0]);
        return 0;
    case 8:  /* SPTan(LONG fnum1) -> LONG  [-48] */
        r->d[0] = (ULONG)SPTan((LONG)r->d[0]);
        return 0;
    case 10:  /* SPSinh(LONG fnum1) -> LONG  [-60] */
        r->d[0] = (ULONG)SPSinh((LONG)r->d[0]);
        return 0;
    case 11:  /* SPCosh(LONG fnum1) -> LONG  [-66] */
        r->d[0] = (ULONG)SPCosh((LONG)r->d[0]);
        return 0;
    case 12:  /* SPTanh(LONG fnum1) -> LONG  [-72] */
        r->d[0] = (ULONG)SPTanh((LONG)r->d[0]);
        return 0;
    case 13:  /* SPExp(LONG fnum1) -> LONG  [-78] */
        r->d[0] = (ULONG)SPExp((LONG)r->d[0]);
        return 0;
    case 14:  /* SPLog(LONG fnum1) -> LONG  [-84] */
        r->d[0] = (ULONG)SPLog((LONG)r->d[0]);
        return 0;
    case 15:  /* SPPow(LONG fnum1, LONG fnum2) -> LONG  [-90] */
        r->d[0] = (ULONG)SPPow((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 16:  /* SPSqrt(LONG fnum1) -> LONG  [-96] */
        r->d[0] = (ULONG)SPSqrt((LONG)r->d[0]);
        return 0;
    case 17:  /* SPTieee(LONG fnum) -> LONG  [-102] */
        r->d[0] = (ULONG)SPTieee((LONG)r->d[0]);
        return 0;
    case 18:  /* SPFieee(LONG ieeenum) -> LONG  [-108] */
        r->d[0] = (ULONG)SPFieee((LONG)r->d[0]);
        return 0;
    case 19:  /* SPAsin(LONG fnum1) -> LONG  [-114] */
        r->d[0] = (ULONG)SPAsin((LONG)r->d[0]);
        return 0;
    case 20:  /* SPAcos(LONG fnum1) -> LONG  [-120] */
        r->d[0] = (ULONG)SPAcos((LONG)r->d[0]);
        return 0;
    case 21:  /* SPLog10(LONG fnum1) -> LONG  [-126] */
        r->d[0] = (ULONG)SPLog10((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
