/* GENERATED by graft/gen-emu68k-bridge from rom/utility/utility.conf - do not edit.
 *
 * Derived crossings for utility.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/utility.h>

#include "emu68k_gen.h"

int emu68k_gen_utility(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct UtilityBase *UtilityBase = base;
    (void)r; (void)guest0; (void)UtilityBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 17:  /* CallHookPkt(struct Hook * hook, APTR object, APTR paramPacket) -> IPTR  [-102] */
    {
        struct Emu68kHookBridge emu_hook_0;
        if (emu68k_hook_prepare(guest0, r->a[0], &emu_hook_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)CallHookPkt((struct Hook *)&emu_hook_0.native,
              (APTR)(IPTR)r->a[2],
              (APTR)(IPTR)r->a[1]);   /* narrowed: an integer, never an address */
        if (emu68k_hook_finish(&emu_hook_0, err, errlen) < 0)
            return 1;
            return 0;
    }
    case 23:  /* SMult32(LONG arg1, LONG arg2) -> LONG  [-138] */
        r->d[0] = (ULONG)SMult32((LONG)r->d[0],
              (LONG)r->d[1]);
        return 0;
    case 24:  /* UMult32(ULONG arg1, ULONG arg2) -> ULONG  [-144] */
        r->d[0] = (ULONG)UMult32((ULONG)r->d[0],
              (ULONG)r->d[1]);
        return 0;
    case 27:  /* Stricmp(CONST_STRPTR string1, CONST_STRPTR string2) -> LONG  [-162] */
        r->d[0] = (ULONG)Stricmp((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]));
        return 0;
    case 28:  /* Strnicmp(CONST_STRPTR string1, CONST_STRPTR string2, LONG length) -> LONG  [-168] */
        r->d[0] = (ULONG)Strnicmp((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]),
              (LONG)r->d[0]);
        return 0;
    case 29:  /* ToUpper(ULONG character) -> UBYTE  [-174] */
        r->d[0] = (ULONG)ToUpper((ULONG)r->d[0]);
        return 0;
    case 30:  /* ToLower(ULONG character) -> UBYTE  [-180] */
        r->d[0] = (ULONG)ToLower((ULONG)r->d[0]);
        return 0;
    case 45:  /* GetUniqueID(void) -> ULONG  [-270] */
        r->d[0] = (ULONG)GetUniqueID();
        return 0;
    case 50:  /* Strlcpy(STRPTR destination, CONST_STRPTR source, LONG size) -> LONG  [-300] */
        r->d[0] = (ULONG)Strlcpy((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]),
              (LONG)r->d[0]);
        return 0;
    case 51:  /* Strlcat(STRPTR destination, CONST_STRPTR source, LONG size) -> LONG  [-306] */
        r->d[0] = (ULONG)Strlcat((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->a[1]),
              (LONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
