/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/icon/icon.conf - do not edit.
 *
 * Tier 1 crossings for icon.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/icon.h>

#include "emu68k_gen.h"

int emu68k_gen_icon(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *IconBase = base;
    (void)r; (void)guest0; (void)IconBase;

    switch (lvo)
    {
    case 17:  /* MatchToolValue(UBYTE * typeString, UBYTE * value) -> BOOL  [-102] */
        r->d[0] = (ULONG)MatchToolValue((UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (UBYTE *)EMU_GPTR(guest0, r->a[1]));
        return 0;
    case 23:  /* DeleteDiskObject(UBYTE * name) -> BOOL  [-138] */
        r->d[0] = (ULONG)DeleteDiskObject((UBYTE *)EMU_GPTR(guest0, r->a[0]));
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
