/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathffp/mathffp.conf - do not edit.
 *
 * Tier 1 crossings for mathffp.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/mathffp.h>

#include "emu68k_gen.h"

int emu68k_gen_mathffp(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *MathBase = base;
    (void)r; (void)guest0; (void)MathBase;

    switch (lvo)
    {
    case 5:  /* SPFix(LONG fnum) -> LONG  [-30] */
        r->d[0] = (ULONG)SPFix((LONG)r->d[0]);
        return 0;
    case 6:  /* SPFlt(LONG inum) -> LONG  [-36] */
        r->d[0] = (ULONG)SPFlt((LONG)r->d[0]);
        return 0;
    case 7:  /* SPCmp(LONG fnum1, LONG fnum2) -> LONG  [-42] */
        r->d[0] = (ULONG)SPCmp((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 8:  /* SPTst(LONG fnum) -> LONG  [-48] */
        r->d[0] = (ULONG)SPTst((LONG)r->d[1]);
        return 0;
    case 9:  /* SPAbs(LONG fnum1) -> LONG  [-54] */
        r->d[0] = (ULONG)SPAbs((LONG)r->d[0]);
        return 0;
    case 10:  /* SPNeg(LONG fnum1) -> LONG  [-60] */
        r->d[0] = (ULONG)SPNeg((LONG)r->d[0]);
        return 0;
    case 11:  /* SPAdd(LONG fnum1, LONG fnum2) -> LONG  [-66] */
        r->d[0] = (ULONG)SPAdd((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 12:  /* SPSub(LONG fnum1, LONG fnum2) -> LONG  [-72] */
        r->d[0] = (ULONG)SPSub((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 13:  /* SPMul(LONG fnum1, LONG fnum2) -> LONG  [-78] */
        r->d[0] = (ULONG)SPMul((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 14:  /* SPDiv(LONG fnum1, LONG fnum2) -> LONG  [-84] */
        r->d[0] = (ULONG)SPDiv((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 15:  /* SPFloor(LONG y) -> LONG  [-90] */
        r->d[0] = (ULONG)SPFloor((LONG)r->d[0]);
        return 0;
    case 16:  /* SPCeil(LONG y) -> LONG  [-96] */
        r->d[0] = (ULONG)SPCeil((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
