/* GENERATED by graft/gen-emu68k-bridge - do not edit.
 *
 * The generated half of the 68k -> native library bridge. One entry point per
 * library; each returns 0 when it served the call and 1 when the vector is not
 * one it covers, so the hand-written bridge stays in charge of everything that
 * needs judgement.
 */

#ifndef EMU68K_GEN_H
#define EMU68K_GEN_H

#include <exec/types.h>
#include <dos/dos.h>          /* BPTR, for the handle table below */
#include <utility/hooks.h>
#include <intuition/classes.h>

struct TagItem;
struct EmuField;

struct Emu68kHookBridge
{
    struct Hook native;
    APTR state;
    ULONG guest_hook;
    ULONG entry;
    LONG failed;
    char error[160];
};

struct Emu68kBoopsiBridge
{
    struct Hook saved_dispatcher;
    APTR native_class;
    APTR state;
    ULONG guest_class;
    ULONG entry;
    LONG failed;
    char error[160];
};

/* The leading, stable part of the engine's 68k register file. The engine owns
 * the full struct; only these two arrays are contractual here. */
struct Emu68kRegs
{
    ULONG d[8];
    ULONG a[8];
};

/* A guest pointer becomes a host pointer by adding the guest base. Only memory
 * inside the guest arena may be handed to a native call this way. */
#define EMU_GPTR(g0, a)  ((APTR)((a) ? (UBYTE *)(g0) + (ULONG)(a) : NULL))

/* A BPTR cannot cross as itself: a native one is 64-bit and a 68k register is
 * not. These map between the guest's 32-bit token and the native BPTR it
 * stands for; both live in emu68k_oscall.c, which owns the table. */
BPTR  emu68k_handle_bptr(APTR guest0, ULONG token);
ULONG emu68k_handle_token(APTR guest0, BPTR b);
#define EMU_HANDLE(g0, t)  emu68k_handle_bptr((g0), (ULONG)(t))
#define EMU_TOKEN(g0, b)   emu68k_handle_token((g0), (b))

/* A 68k IEEE double is the raw bit pattern in a register pair, high half first.
 * Nothing is converted: the same 64 bits are handed to a native double, which is
 * the same format. The union is there so it is a reinterpretation and not a
 * numeric conversion. */
static inline double emu68k_double_in(ULONG hi, ULONG lo)
{
    union { double d; UQUAD q; } u;
    u.q = ((UQUAD)hi << 32) | (UQUAD)lo;
    return u.d;
}
static inline void emu68k_double_out(double v, ULONG *hi, ULONG *lo)
{
    union { double d; UQUAD q; } u;
    u.d = v;
    *hi = (ULONG)(u.q >> 32);
    *lo = (ULONG)u.q;
}

UQUAD emu68k_scalar_from_guest(APTR guest0, ULONG addr, UBYTE width);
void  emu68k_scalar_to_guest(APTR guest0, ULONG addr, UBYTE width, UQUAD value);

/* Native OS objects cross as typed, per-run tokens. The table preserves
 * identity and reference counts, rejects stale/wrong-type tokens, and owns a
 * cleanup callback so objects still live at program exit are released. */
typedef void (*EmuObjectCleanup)(APTR base, APTR object);
LONG emu68k_object_from_guest(APTR guest0, ULONG token, UWORD type,
                              BOOL nullable, const char *type_name,
                              APTR *native, char *err, ULONG errlen);
LONG emu68k_object_to_guest(APTR guest0, APTR native, UWORD type,
                            APTR base, EmuObjectCleanup cleanup,
                            const char *type_name, ULONG *token,
                            char *err, ULONG errlen);
LONG emu68k_object_to_guest_facade(APTR guest0, APTR native, UWORD type,
                                   APTR base, EmuObjectCleanup cleanup,
                                   const char *type_name, ULONG facade_size,
                                   const struct EmuField *fields, int field_count,
                                   ULONG *token, char *err, ULONG errlen);
void emu68k_object_release(APTR guest0, ULONG token, UWORD type);
void emu68k_object_consume(APTR guest0, ULONG token, UWORD type);
LONG emu68k_hook_prepare(APTR guest0, ULONG guest_hook,
                         struct Emu68kHookBridge *bridge,
                         char *err, ULONG errlen);
LONG emu68k_hook_finish(const struct Emu68kHookBridge *bridge,
                        char *err, ULONG errlen);
LONG emu68k_boopsi_prepare(APTR guest0, ULONG guest_class, APTR native_class,
                           struct Emu68kBoopsiBridge *bridge,
                           char *err, ULONG errlen);
LONG emu68k_boopsi_finish(struct Emu68kBoopsiBridge *bridge,
                          char *err, ULONG errlen);

/* Policy-compiled TagItem values. A domain names every accepted tag and the
 * type of ti_Data. Unknown/refused tags fail the crossing; they are never
 * forwarded as if every IPTR were a scalar. */
#define EMU_TAG_U32     0
#define EMU_TAG_CSTR    1
#define EMU_TAG_REFUSE  2
#define EMU_TAG_STRUCT  3   /* ti_Data is a guest pointer to a value structure */
struct EmuTagDesc
{
    ULONG tag;
    UBYTE kind;
    const char *name;
    /* EMU_TAG_STRUCT only: how to rebuild what ti_Data points at. The native
     * copy lives in the caller's scratch and is valid for the call, which is
     * why a structure tag is only described for calls that consume it rather
     * than retain it. */
    const struct EmuField *fields;
    UWORD nfields;
    UWORD guest_size;
    UWORD native_size;
};
struct EmuTagDomain
{
    const struct EmuTagDesc *tags;
    UWORD count;
    const char *name;
};
LONG emu68k_tags_to_native(APTR guest0, ULONG guest_tags,
                           const struct EmuTagDomain *domain,
                           struct TagItem *native_tags, ULONG capacity,
                           APTR scratch, ULONG scratch_size,
                           char *err, ULONG errlen);

LONG emu68k_require_guest_range(ULONG guest_addr, ULONG length,
                                const char *what, char *err, ULONG errlen);
void emu68k_to_guest(APTR guest0, ULONG gbase, const void *native,
                     const struct EmuField *fields, int count);
void emu68k_from_guest(APTR guest0, ULONG gbase, void *native,
                       const struct EmuField *fields, int count);
/* The same conversions bounded by how much of the GUEST structure the caller
 * asked for; a field straddling the bound is left alone rather than clipped. */
#define EMU_NO_LIMIT 0xffffffffUL
void emu68k_to_guest_sized(APTR guest0, ULONG gbase, const void *native,
                           const struct EmuField *fields, int count, ULONG limit);
void emu68k_from_guest_sized(APTR guest0, ULONG gbase, void *native,
                             const struct EmuField *fields, int count, ULONG limit);
#define EMU_NFIELDS(a) ((int)(sizeof(a) / sizeof((a)[0])))

enum
{
    EMU_OBJ_Catalog = 1,
    EMU_OBJ_Locale = 2,
    EMU_OBJ_DiskObject = 3,
    EMU_OBJ_Class = 4,
    EMU_OBJ_Object = 5,
    EMU_OBJ_SignalSemaphore = 6,
    EMU_OBJ_MsgPort = 7,
    EMU_OBJ_Region = 8,
    EMU_OBJ_Screen = 9,
    EMU_OBJ_AslRequest = 10,
    EMU_OBJ_TextFont = 11,
};
int emu68k_gen_exec(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_dos(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_utility(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_intuition(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_graphics(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_layers(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_gadtools(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_asl(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_icon(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_iffparse(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_commodities(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_diskfont(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_locale(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_keymap(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_datatypes(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_expansion(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_cybergraphics(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathffp(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathieeesingbas(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathieeedoubbas(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathieeesingtrans(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathieeedoubtrans(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_mathtrans(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
int emu68k_gen_workbench(int lvo, struct Emu68kRegs *r,
                  APTR guest0, APTR base,
                  char *err, ULONG errlen);
/* name, generated entry point, and where its base comes from. */
#define EMU68K_GEN_LIBS(X) \
    X("exec.library", emu68k_gen_exec, GENBASE_EXEC) \
    X("dos.library", emu68k_gen_dos, GENBASE_DOS) \
    X("utility.library", emu68k_gen_utility, GENBASE_OPEN) \
    X("intuition.library", emu68k_gen_intuition, GENBASE_OPEN) \
    X("graphics.library", emu68k_gen_graphics, GENBASE_OPEN) \
    X("layers.library", emu68k_gen_layers, GENBASE_OPEN) \
    X("gadtools.library", emu68k_gen_gadtools, GENBASE_OPEN) \
    X("asl.library", emu68k_gen_asl, GENBASE_OPEN) \
    X("icon.library", emu68k_gen_icon, GENBASE_OPEN) \
    X("iffparse.library", emu68k_gen_iffparse, GENBASE_OPEN) \
    X("commodities.library", emu68k_gen_commodities, GENBASE_OPEN) \
    X("diskfont.library", emu68k_gen_diskfont, GENBASE_OPEN) \
    X("locale.library", emu68k_gen_locale, GENBASE_OPEN) \
    X("keymap.library", emu68k_gen_keymap, GENBASE_OPEN) \
    X("datatypes.library", emu68k_gen_datatypes, GENBASE_OPEN) \
    X("expansion.library", emu68k_gen_expansion, GENBASE_OPEN) \
    X("cybergraphics.library", emu68k_gen_cybergraphics, GENBASE_OPEN) \
    X("mathffp.library", emu68k_gen_mathffp, GENBASE_OPEN) \
    X("mathieeesingbas.library", emu68k_gen_mathieeesingbas, GENBASE_OPEN) \
    X("mathieeedoubbas.library", emu68k_gen_mathieeedoubbas, GENBASE_OPEN) \
    X("mathieeesingtrans.library", emu68k_gen_mathieeesingtrans, GENBASE_OPEN) \
    X("mathieeedoubtrans.library", emu68k_gen_mathieeedoubtrans, GENBASE_OPEN) \
    X("mathtrans.library", emu68k_gen_mathtrans, GENBASE_OPEN) \
    X("workbench.library", emu68k_gen_workbench, GENBASE_OPEN) \
    /* end */
#endif /* EMU68K_GEN_H */
