/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/cgfx/cybergraphics.conf - do not edit.
 *
 * Tier 1 crossings for cybergraphics.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/cybergraphics.h>

#include "emu68k_gen.h"

int emu68k_gen_cybergraphics(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *CyberGfxBase = base;
    (void)r; (void)guest0; (void)CyberGfxBase;

    switch (lvo)
    {
    case 9:  /* IsCyberModeID(ULONG modeID) -> BOOL  [-54] */
        r->d[0] = (ULONG)IsCyberModeID((ULONG)r->d[0]);
        return 0;
    case 15:  /* GetCyberIDAttr(ULONG attribute, ULONG DisplayModeID) -> ULONG  [-90] */
        r->d[0] = (ULONG)GetCyberIDAttr((ULONG)r->d[0],
              (ULONG)r->d[1]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
