/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/commodities/commodities.conf - do not edit.
 *
 * Tier 1 crossings for commodities.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/commodities.h>

#include "emu68k_gen.h"

int emu68k_gen_commodities(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *CxBase = base;
    (void)r; (void)guest0; (void)CxBase;

    switch (lvo)
    {
    case 32:  /* BrokerCommand(STRPTR name, ULONG command) -> ULONG  [-192] */
        r->d[0] = (ULONG)BrokerCommand((STRPTR)EMU_GPTR(guest0, r->a[0]),
              (ULONG)r->d[0]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
