/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathieeesingtrans/mathieeesingtrans.conf - do not edit.
 *
 * Derived crossings for mathieeesingtrans.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/mathieeesingtrans.h>

#include "emu68k_gen.h"

int emu68k_gen_mathieeesingtrans(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *MathIeeeSingTransBase = base;
    (void)r; (void)guest0; (void)MathIeeeSingTransBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 5:  /* IEEESPAtan(LONG y) -> LONG  [-30] */
        r->d[0] = (ULONG)IEEESPAtan((LONG)r->d[0]);
        return 0;
    case 6:  /* IEEESPSin(LONG y) -> LONG  [-36] */
        r->d[0] = (ULONG)IEEESPSin((LONG)r->d[0]);
        return 0;
    case 7:  /* IEEESPCos(LONG y) -> LONG  [-42] */
        r->d[0] = (ULONG)IEEESPCos((LONG)r->d[0]);
        return 0;
    case 8:  /* IEEESPTan(LONG y) -> LONG  [-48] */
        r->d[0] = (ULONG)IEEESPTan((LONG)r->d[0]);
        return 0;
    case 9:  /* IEEESPSincos: no crossing [-54] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: mathieeesingtrans.library.IEEESPSincos needs LONG * described");
        r->d[0] = 0;
        return 1;
    case 10:  /* IEEESPSinh(LONG y) -> LONG  [-60] */
        r->d[0] = (ULONG)IEEESPSinh((LONG)r->d[0]);
        return 0;
    case 11:  /* IEEESPCosh(LONG y) -> LONG  [-66] */
        r->d[0] = (ULONG)IEEESPCosh((LONG)r->d[0]);
        return 0;
    case 12:  /* IEEESPTanh(LONG y) -> LONG  [-72] */
        r->d[0] = (ULONG)IEEESPTanh((LONG)r->d[0]);
        return 0;
    case 13:  /* IEEESPExp(LONG y) -> LONG  [-78] */
        r->d[0] = (ULONG)IEEESPExp((LONG)r->d[0]);
        return 0;
    case 14:  /* IEEESPLog(LONG y) -> LONG  [-84] */
        r->d[0] = (ULONG)IEEESPLog((LONG)r->d[0]);
        return 0;
    case 15:  /* IEEESPPow(LONG x, LONG y) -> LONG  [-90] */
        r->d[0] = (ULONG)IEEESPPow((LONG)r->d[1],
              (LONG)r->d[0]);
        return 0;
    case 16:  /* IEEESPSqrt(LONG y) -> LONG  [-96] */
        r->d[0] = (ULONG)IEEESPSqrt((LONG)r->d[0]);
        return 0;
    case 17:  /* IEEESPTieee(LONG y) -> LONG  [-102] */
        r->d[0] = (ULONG)IEEESPTieee((LONG)r->d[0]);
        return 0;
    case 18:  /* IEEESPFieee(LONG y) -> LONG  [-108] */
        r->d[0] = (ULONG)IEEESPFieee((LONG)r->d[0]);
        return 0;
    case 19:  /* IEEESPAsin(LONG y) -> LONG  [-114] */
        r->d[0] = (ULONG)IEEESPAsin((LONG)r->d[0]);
        return 0;
    case 20:  /* IEEESPAcos(LONG y) -> LONG  [-120] */
        r->d[0] = (ULONG)IEEESPAcos((LONG)r->d[0]);
        return 0;
    case 21:  /* IEEESPLog10(LONG y) -> LONG  [-126] */
        r->d[0] = (ULONG)IEEESPLog10((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
