/* GENERATED by graft/gen-emu68k-bridge from rom/graphics/graphics.conf - do not edit.
 *
 * Derived crossings for graphics.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/graphics.h>
#include <string.h>
#include <stdio.h>
#include <graphics/displayinfo.h>
#include <graphics/modeid.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_graphics_best_mode[] =
{
    { BIDTAG_DIPFMustHave, EMU_TAG_U32, "BIDTAG_DIPFMustHave", NULL, 0, 0, 0 },
    { BIDTAG_DIPFMustNotHave, EMU_TAG_U32, "BIDTAG_DIPFMustNotHave", NULL, 0, 0, 0 },
    { BIDTAG_ViewPort, EMU_TAG_REFUSE, "BIDTAG_ViewPort", NULL, 0, 0, 0 },
    { BIDTAG_NominalWidth, EMU_TAG_U32, "BIDTAG_NominalWidth", NULL, 0, 0, 0 },
    { BIDTAG_NominalHeight, EMU_TAG_U32, "BIDTAG_NominalHeight", NULL, 0, 0, 0 },
    { BIDTAG_DesiredWidth, EMU_TAG_U32, "BIDTAG_DesiredWidth", NULL, 0, 0, 0 },
    { BIDTAG_DesiredHeight, EMU_TAG_U32, "BIDTAG_DesiredHeight", NULL, 0, 0, 0 },
    { BIDTAG_Depth, EMU_TAG_U32, "BIDTAG_Depth", NULL, 0, 0, 0 },
    { BIDTAG_MonitorID, EMU_TAG_U32, "BIDTAG_MonitorID", NULL, 0, 0, 0 },
    { BIDTAG_SourceID, EMU_TAG_U32, "BIDTAG_SourceID", NULL, 0, 0, 0 },
    { BIDTAG_RedBits, EMU_TAG_U32, "BIDTAG_RedBits", NULL, 0, 0, 0 },
    { BIDTAG_BlueBits, EMU_TAG_U32, "BIDTAG_BlueBits", NULL, 0, 0, 0 },
    { BIDTAG_GreenBits, EMU_TAG_U32, "BIDTAG_GreenBits", NULL, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_graphics_best_mode =
{
    emu_tagdesc_graphics_best_mode, 13, "graphics.best_mode"
};

static void emu_object_cleanup_TextFont(APTR emu_base, APTR emu_object)
{
    struct GfxBase *GfxBase = emu_base;
    CloseFont((struct TextFont *)emu_object);
}

static void emu_object_cleanup_Region(APTR emu_base, APTR emu_object)
{
    struct GfxBase *GfxBase = emu_base;
    DisposeRegion((struct Region *)emu_object);
}

int emu68k_gen_graphics(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct GfxBase *GfxBase = base;
    (void)r; (void)guest0; (void)GfxBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 12:  /* OpenFont(const struct TextAttr * textAttr) -> struct TextFont *  [-72] */
    {
        struct TextAttr emu_struct_0;
        if (emu68k_require_guest_range(r->a[0], M68K_TextAttr_SIZEOF,
                                         "OpenFont.textAttr", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->a[0], &emu_struct_0,
                             emu_fields_TextAttr, EMU_NFIELDS(emu_fields_TextAttr), M68K_TextAttr_SIZEOF);
        APTR emu_result = (APTR)OpenFont((const struct TextAttr *)&emu_struct_0);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_TextFont,
                                             base, emu_object_cleanup_TextFont,
                                             "TextFont", M68K_TextFont_SIZEOF,
                                             emu_fields_TextFont, EMU_NFIELDS(emu_fields_TextFont),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 13:  /* CloseFont(struct TextFont * textFont) -> void  [-78] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_TextFont, 0,
                                        "TextFont", &emu_object_0, err, errlen) < 0)
            return 1;
            CloseFont((struct TextFont *)emu_object_0);
        emu68k_object_consume(guest0, r->a[1], EMU_OBJ_TextFont);
            return 0;
    }
    case 33:  /* InitRastPort(struct RastPort * rp) -> void  [-198] */
    {
        struct RastPort emu_struct_0;
        if (emu68k_require_guest_range(r->a[1], M68K_RastPort_SIZEOF,
                                         "InitRastPort.rp", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
            InitRastPort((struct RastPort *)&emu_struct_0);
        memset(EMU_GPTR(guest0, r->a[1]), 0, M68K_RastPort_SIZEOF);
        emu68k_to_guest_sized(guest0, r->a[1], &emu_struct_0,
                           emu_fields_RastPort, EMU_NFIELDS(emu_fields_RastPort), M68K_RastPort_SIZEOF);
            return 0;
    }
    case 38:  /* WaitBlit(void) -> void  [-228] */
        WaitBlit();
        return 0;
    case 45:  /* WaitTOF(void) -> void  [-270] */
        WaitTOF();
        return 0;
    case 64:  /* VBeamPos(void) -> LONG  [-384] */
        r->d[0] = (ULONG)VBeamPos();
        return 0;
    case 65:  /* InitBitMap(struct BitMap * bm, BYTE depth, UWORD width, UWORD height) -> void  [-390] */
    {
        struct BitMap emu_struct_0;
        if (emu68k_require_guest_range(r->a[0], M68K_BitMap_SIZEOF,
                                         "InitBitMap.bm", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
            InitBitMap((struct BitMap *)&emu_struct_0,
              (BYTE)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2]);
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap), M68K_BitMap_SIZEOF);
            return 0;
    }
    case 69:  /* FreeSprite(WORD pick) -> void  [-414] */
        FreeSprite((WORD)r->d[0]);
        return 0;
    case 76:  /* OwnBlitter(void) -> void  [-456] */
        OwnBlitter();
        return 0;
    case 77:  /* DisownBlitter(void) -> void  [-462] */
        DisownBlitter();
        return 0;
    case 84:  /* AndRectRegion(struct Region * Reg, struct Rectangle * Rect) -> void  [-504] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        struct Rectangle emu_struct_1;
        if (emu68k_require_guest_range(r->a[1], M68K_Rectangle_SIZEOF,
                                         "AndRectRegion.Rect", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
            AndRectRegion((struct Region *)emu_object_0,
              (struct Rectangle *)&emu_struct_1);
            return 0;
    }
    case 85:  /* OrRectRegion(struct Region * Reg, struct Rectangle * Rect) -> BOOL  [-510] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        struct Rectangle emu_struct_1;
        if (emu68k_require_guest_range(r->a[1], M68K_Rectangle_SIZEOF,
                                         "OrRectRegion.Rect", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
            r->d[0] = (ULONG)OrRectRegion((struct Region *)emu_object_0,
              (struct Rectangle *)&emu_struct_1);
            return 0;
    }
    case 86:  /* NewRegion(void) -> struct Region *  [-516] */
    {
        APTR emu_result = (APTR)NewRegion();
        if (emu68k_object_to_guest(guest0, emu_result, EMU_OBJ_Region,
                                      base, emu_object_cleanup_Region,
                                      "Region", &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 87:  /* ClearRectRegion(struct Region * Reg, struct Rectangle * Rect) -> BOOL  [-522] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        struct Rectangle emu_struct_1;
        if (emu68k_require_guest_range(r->a[1], M68K_Rectangle_SIZEOF,
                                         "ClearRectRegion.Rect", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
            r->d[0] = (ULONG)ClearRectRegion((struct Region *)emu_object_0,
              (struct Rectangle *)&emu_struct_1);
            return 0;
    }
    case 88:  /* ClearRegion(struct Region * region) -> void  [-528] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
            ClearRegion((struct Region *)emu_object_0);
            return 0;
    }
    case 89:  /* DisposeRegion(struct Region * region) -> void  [-534] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 1,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
            DisposeRegion((struct Region *)emu_object_0);
        emu68k_object_consume(guest0, r->a[0], EMU_OBJ_Region);
            return 0;
    }
    case 93:  /* XorRectRegion(struct Region * Reg, struct Rectangle * Rect) -> BOOL  [-558] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        struct Rectangle emu_struct_1;
        if (emu68k_require_guest_range(r->a[1], M68K_Rectangle_SIZEOF,
                                         "XorRectRegion.Rect", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->a[1], &emu_struct_1,
                             emu_fields_Rectangle, EMU_NFIELDS(emu_fields_Rectangle), M68K_Rectangle_SIZEOF);
            r->d[0] = (ULONG)XorRectRegion((struct Region *)emu_object_0,
              (struct Rectangle *)&emu_struct_1);
            return 0;
    }
    case 114:  /* ScalerDiv(UWORD factor, UWORD numerator, UWORD denominator) -> UWORD  [-684] */
        r->d[0] = (ULONG)ScalerDiv((UWORD)r->d[0],
              (UWORD)r->d[1],
              (UWORD)r->d[2]);
        return 0;
    case 121:  /* FindDisplayInfo(ULONG ID) -> DisplayInfoHandle  [-726] */
    {
        APTR emu_result = (APTR)FindDisplayInfo((ULONG)r->d[0]);
        if (emu68k_object_to_guest(guest0, emu_result, EMU_OBJ_DisplayInfoHandle,
                                      base, NULL,
                                      "DisplayInfoHandle", &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 122:  /* NextDisplayInfo(ULONG last_ID) -> ULONG  [-732] */
        r->d[0] = (ULONG)NextDisplayInfo((ULONG)r->d[0]);
        return 0;
    case 126:  /* GetDisplayInfoData(DisplayInfoHandle handle, UBYTE * buf, ULONG size, ULONG tagID, ULONG ID) -> ULONG  [-756] */
    {
        struct DimensionInfo emu_tagged_1_DimensionInfo;
        APTR emu_tagged_native_1 = NULL;
        const struct EmuField *emu_tagged_fields_1 = NULL;
        ULONG emu_tagged_nfields_1 = 0;
        ULONG emu_tagged_native_size_1 = 0;
        ULONG emu_tagged_guest_size_1 = 0;
        switch ((ULONG)r->d[1])
        {
        case DTAG_DIMS:
            memset(&emu_tagged_1_DimensionInfo, 0, sizeof(emu_tagged_1_DimensionInfo));
            emu_tagged_native_1 = &emu_tagged_1_DimensionInfo;
            emu_tagged_fields_1 = emu_fields_DimensionInfo;
            emu_tagged_nfields_1 = EMU_NFIELDS(emu_fields_DimensionInfo);
            emu_tagged_native_size_1 = sizeof(struct DimensionInfo);
            emu_tagged_guest_size_1 = M68K_DimensionInfo_SIZEOF;
            break;
        default:
            if (err && errlen)
                snprintf(err, errlen, "GetDisplayInfoData.buf: unsupported tag %08lx",
                         (unsigned long)r->d[1]);
            return 1;
        }
        ULONG emu_tagged_limit_1 = (ULONG)r->d[0];
        if (emu_tagged_limit_1 > emu_tagged_guest_size_1)
            emu_tagged_limit_1 = emu_tagged_guest_size_1;
        if (emu68k_require_guest_range(r->a[1], emu_tagged_limit_1,
                                         "GetDisplayInfoData.buf", err, errlen) < 0)
            return 1;
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_DisplayInfoHandle, 1,
                                        "DisplayInfoHandle", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)GetDisplayInfoData((DisplayInfoHandle)emu_object_0,
              (UBYTE *)emu_tagged_native_1,
              (ULONG)emu_tagged_native_size_1,
              (ULONG)r->d[1],
              (ULONG)r->d[2]);
        if (r->d[0])
        {
            memset(EMU_GPTR(guest0, r->a[1]), 0, emu_tagged_limit_1);
            emu68k_to_guest_sized(guest0, r->a[1], emu_tagged_native_1,
                               emu_tagged_fields_1, emu_tagged_nfields_1, emu_tagged_limit_1);
            r->d[0] = emu_tagged_limit_1;
        }
            return 0;
    }
    case 133:  /* ModeNotAvailable(ULONG modeID) -> ULONG  [-798] */
        r->d[0] = (ULONG)ModeNotAvailable((ULONG)r->d[0]);
        return 0;
    case 147:  /* LoadRGB32(struct ViewPort * vp, const ULONG * table) -> void  [-882] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_ViewPort, 0,
                                        "ViewPort", &emu_object_0, err, errlen) < 0)
            return 1;
        ULONG emu_array_size_1 = sizeof(ULONG) * 1024;
        APTR emu_array_scratch_1 = NULL;
        if (r->a[1])
        {
            emu_array_scratch_1 = emu68k_scratch_alloc(
                emu_array_size_1, err, errlen);
            if (!emu_array_scratch_1)
            {
                return 1;
            }
            if (emu68k_rgb32_to_native(guest0, r->a[1],
                    (ULONG *)emu_array_scratch_1, 1024,
                    "LoadRGB32.table", err, errlen) < 0)
            {
                emu68k_scratch_free(emu_array_scratch_1, emu_array_size_1);
                return 1;
            }
        }
            LoadRGB32((struct ViewPort *)emu_object_0,
              (const ULONG *)emu_array_scratch_1);
        if (emu_array_scratch_1)
            emu68k_scratch_free(emu_array_scratch_1, emu_array_size_1);
            return 0;
    }
    case 148:  /* SetChipRev(ULONG ChipRev) -> ULONG  [-888] */
        r->d[0] = (ULONG)SetChipRev((ULONG)r->d[0]);
        return 0;
    case 158:  /* ReleasePen(struct ColorMap * cm, ULONG n) -> void  [-948] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_ColorMap, 0,
                                        "ColorMap", &emu_object_0, err, errlen) < 0)
            return 1;
            ReleasePen((struct ColorMap *)emu_object_0,
              (ULONG)r->d[0]);
            return 0;
    }
    case 159:  /* ObtainPen(struct ColorMap * cm, ULONG n, ULONG r, ULONG g, ULONG b, ULONG flags) -> LONG  [-954] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_ColorMap, 0,
                                        "ColorMap", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ObtainPen((struct ColorMap *)emu_object_0,
              (ULONG)r->d[0],
              (ULONG)r->d[1],
              (ULONG)r->d[2],
              (ULONG)r->d[3],
              (ULONG)r->d[4]);
            return 0;
    }
    case 175:  /* BestModeIDA(struct TagItem * TagItems) -> ULONG  [-1050] */
    {
        struct TagItem emu_tags_0[33];
        if (emu68k_tags_to_native(guest0, r->a[0], &emu_tagdomain_graphics_best_mode,
                                     emu_tags_0, 33, NULL, 0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)BestModeIDA((struct TagItem *)(r->a[0] ? emu_tags_0 : NULL));
            return 0;
    }
    case 181:  /* SetRegion(struct Region * src, struct Region * dest) -> BOOL  [-1086] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_1, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)SetRegion((struct Region *)emu_object_0,
              (struct Region *)emu_object_1);
            return 0;
    }
    case 183:  /* AreRegionsEqual(struct Region * R1, struct Region * R2) -> BOOL  [-1098] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_1, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)AreRegionsEqual((struct Region *)emu_object_0,
              (struct Region *)emu_object_1);
            return 0;
    }
    case 184:  /* IsPointInRegion(struct Region * Reg, WORD x, WORD y) -> BOOL  [-1104] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Region, 0,
                                        "Region", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)IsPointInRegion((struct Region *)emu_object_0,
              (WORD)r->d[0],
              (WORD)r->d[1]);
            return 0;
    }
    }
    return 1;   /* no safe generated crossing for this vector */
}
