/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/mathieeedoubtrans/mathieeedoubtrans.conf - do not edit.
 *
 * Derived crossings for mathieeedoubtrans.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/mathieeedoubtrans.h>

#include "emu68k_gen.h"

int emu68k_gen_mathieeedoubtrans(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *MathIeeeDoubTransBase = base;
    (void)r; (void)guest0; (void)MathIeeeDoubTransBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 5:  /* IEEEDPAtan(double y) -> double  [-30] */
        emu68k_double_out(IEEEDPAtan(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 6:  /* IEEEDPSin(double y) -> double  [-36] */
        emu68k_double_out(IEEEDPSin(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 7:  /* IEEEDPCos(double y) -> double  [-42] */
        emu68k_double_out(IEEEDPCos(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 8:  /* IEEEDPTan(double y) -> double  [-48] */
        emu68k_double_out(IEEEDPTan(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 9:  /* IEEEDPSincos: no crossing [-54] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: mathieeedoubtrans.library.IEEEDPSincos needs double * described");
        r->d[0] = 0;
        return 1;
    case 10:  /* IEEEDPSinh(double y) -> double  [-60] */
        emu68k_double_out(IEEEDPSinh(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 11:  /* IEEEDPCosh(double y) -> double  [-66] */
        emu68k_double_out(IEEEDPCosh(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 12:  /* IEEEDPTanh(double y) -> double  [-72] */
        emu68k_double_out(IEEEDPTanh(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 13:  /* IEEEDPExp(double y) -> double  [-78] */
        emu68k_double_out(IEEEDPExp(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 14:  /* IEEEDPLog(double y) -> double  [-84] */
        emu68k_double_out(IEEEDPLog(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 15:  /* IEEEDPPow(double x, double y) -> double  [-90] */
        emu68k_double_out(IEEEDPPow(emu68k_double_in(r->d[0], r->d[1]),
              emu68k_double_in(r->d[2], r->d[3])), &r->d[0], &r->d[1]);
        return 0;
    case 16:  /* IEEEDPSqrt(double y) -> double  [-96] */
        emu68k_double_out(IEEEDPSqrt(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 17:  /* IEEEDPTieee(double y) -> LONG  [-102] */
        r->d[0] = (ULONG)IEEEDPTieee(emu68k_double_in(r->d[0], r->d[1]));
        return 0;
    case 18:  /* IEEEDPFieee(LONG y) -> double  [-108] */
        emu68k_double_out(IEEEDPFieee((LONG)r->d[0]), &r->d[0], &r->d[1]);
        return 0;
    case 19:  /* IEEEDPAsin(double y) -> double  [-114] */
        emu68k_double_out(IEEEDPAsin(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 20:  /* IEEEDPAcos(double y) -> double  [-120] */
        emu68k_double_out(IEEEDPAcos(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    case 21:  /* IEEEDPLog10(double y) -> double  [-126] */
        emu68k_double_out(IEEEDPLog10(emu68k_double_in(r->d[0], r->d[1])), &r->d[0], &r->d[1]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
