/* GENERATED by graft/gen-emu68k-bridge from rom/exec/exec.conf - do not edit.
 *
 * Derived crossings for exec.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/exec.h>

#include "emu68k_gen.h"

int emu68k_gen_exec(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct ExecBase *SysBase = base;
    (void)r; (void)guest0; (void)SysBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 36:  /* AvailMem(ULONG attributes) -> IPTR  [-216] */
        r->d[0] = (ULONG)AvailMem((ULONG)r->d[1]);   /* narrowed: an integer, never an address */
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
