/* GENERATED by graft/gen-emu68k-bridge from rom/intuition/intuition.conf - do not edit.
 *
 * Derived crossings for intuition.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/intuition.h>
#include <string.h>
#include <stdio.h>
#include <intuition/screens.h>
#include <intuition/classes.h>
#include <intuition/imageclass.h>
#include <intuition/pointerclass.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

static const struct EmuTagDesc emu_tagdesc_intuition_open_screen[] =
{
    { SA_AutoScroll, EMU_TAG_U32, "SA_AutoScroll", NULL, 0, 0, 0, 0, 0 },
    { SA_Pens, EMU_TAG_U16_FFFF, "SA_Pens", NULL, 0, 32, 0, 0, 0 },
    { SA_Width, EMU_TAG_U32, "SA_Width", NULL, 0, 0, 0, 0, 0 },
    { SA_Height, EMU_TAG_U32, "SA_Height", NULL, 0, 0, 0, 0, 0 },
    { SA_Depth, EMU_TAG_U32, "SA_Depth", NULL, 0, 0, 0, 0, 0 },
    { SA_Overscan, EMU_TAG_U32, "SA_Overscan", NULL, 0, 0, 0, 0, 0 },
    { SA_DisplayID, EMU_TAG_U32, "SA_DisplayID", NULL, 0, 0, 0, 0, 0 },
    { SA_Interleaved, EMU_TAG_U32, "SA_Interleaved", NULL, 0, 0, 0, 0, 0 },
    { SA_Title, EMU_TAG_CSTR, "SA_Title", NULL, 0, 0, 0, 0, 0 },
    { SA_ShowTitle, EMU_TAG_U32, "SA_ShowTitle", NULL, 0, 0, 0, 0, 0 },
    { SA_Colors32, EMU_TAG_RGB32, "SA_Colors32", NULL, 0, 1024, 0, 0, 0 },
    { SA_SharePens, EMU_TAG_U32, "SA_SharePens", NULL, 0, 0, 0, 0, 0 },
    { SA_PubName, EMU_TAG_CSTR, "SA_PubName", NULL, 0, 0, 0, 0, 0 },
    { SA_Font, EMU_TAG_STRUCT, "SA_Font", emu_fields_TextAttr, EMU_NFIELDS(emu_fields_TextAttr),
      M68K_TextAttr_SIZEOF, sizeof(struct TextAttr), 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_intuition_open_screen =
{
    emu_tagdesc_intuition_open_screen, 14, "intuition.open_screen"
};

static const struct EmuTagDesc emu_tagdesc_intuition_new_object[] =
{
    { SYSIA_DrawInfo, EMU_TAG_OBJECT, "SYSIA_DrawInfo", NULL, 0, 0, 0, EMU_OBJ_DrawInfo, 0 },
    { SYSIA_Size, EMU_TAG_U32, "SYSIA_Size", NULL, 0, 0, 0, 0, 0 },
    { SYSIA_Which, EMU_TAG_U32, "SYSIA_Which", NULL, 0, 0, 0, 0, 0 },
    { POINTERA_BitMap, EMU_TAG_STRUCT, "POINTERA_BitMap", emu_fields_BitMap, EMU_NFIELDS(emu_fields_BitMap),
      M68K_BitMap_SIZEOF, sizeof(struct BitMap), 0, 0 },
    { POINTERA_XOffset, EMU_TAG_U32, "POINTERA_XOffset", NULL, 0, 0, 0, 0, 0 },
    { POINTERA_YOffset, EMU_TAG_U32, "POINTERA_YOffset", NULL, 0, 0, 0, 0, 0 },
    { POINTERA_WordWidth, EMU_TAG_U32, "POINTERA_WordWidth", NULL, 0, 0, 0, 0, 0 },
    { POINTERA_XResolution, EMU_TAG_U32, "POINTERA_XResolution", NULL, 0, 0, 0, 0, 0 },
    { POINTERA_YResolution, EMU_TAG_U32, "POINTERA_YResolution", NULL, 0, 0, 0, 0, 0 },
};
static const struct EmuTagDomain emu_tagdomain_intuition_new_object =
{
    emu_tagdesc_intuition_new_object, 9, "intuition.new_object"
};

static void emu_object_cleanup_Screen(APTR emu_base, APTR emu_object)
{
    struct IntuitionBase *IntuitionBase = emu_base;
    CloseScreen((struct Screen *)emu_object);
}

static void emu_object_cleanup_Class(APTR emu_base, APTR emu_object)
{
    struct IntuitionBase *IntuitionBase = emu_base;
    FreeClass((struct IClass *)emu_object);
}

static void emu_object_cleanup_Object(APTR emu_base, APTR emu_object)
{
    struct IntuitionBase *IntuitionBase = emu_base;
    DisposeObject((APTR)emu_object);
}

int emu68k_gen_intuition(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct IntuitionBase *IntuitionBase = base;
    (void)r; (void)guest0; (void)IntuitionBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 11:  /* CloseScreen(struct Screen * screen) -> BOOL  [-66] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Screen, 0,
                                        "Screen", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)CloseScreen((struct Screen *)emu_object_0);
        emu68k_object_release(guest0,
            r->a[0] + M68K_Screen_ViewPort_Next,
            EMU_OBJ_ViewPort);
        emu68k_object_release(guest0,
            (ULONG)emu68k_scalar_from_guest(guest0, r->a[0] + M68K_Screen_ViewPort_ColorMap, 4),
            EMU_OBJ_ColorMap);
        emu68k_object_consume(guest0, r->a[0], EMU_OBJ_Screen);
            return 0;
    }
    case 13:  /* CloseWorkBench(void) -> LONG  [-78] */
        r->d[0] = (ULONG)CloseWorkBench();
        return 0;
    case 14:  /* CurrentTime(ULONG * seconds, ULONG * micros) -> void  [-84] */
    {
        ULONG emu_scalar_0 = 0;
        if (emu68k_require_guest_range(r->a[0], 4,
                                         "CurrentTime.seconds", err, errlen) < 0)
            return 1;
        ULONG emu_scalar_1 = 0;
        if (emu68k_require_guest_range(r->a[1], 4,
                                         "CurrentTime.micros", err, errlen) < 0)
            return 1;
            CurrentTime((ULONG *)&emu_scalar_0,
              (ULONG *)&emu_scalar_1);
        emu68k_scalar_to_guest(guest0, r->a[0], 4, (UQUAD)emu_scalar_0);
        emu68k_scalar_to_guest(guest0, r->a[1], 4, (UQUAD)emu_scalar_1);
            return 0;
    }
    case 15:  /* DisplayAlert(ULONG alertnumber, UBYTE * string, UWORD height) -> BOOL  [-90] */
        r->d[0] = (ULONG)DisplayAlert((ULONG)r->d[0],
              (UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[1]);
        return 0;
    case 17:  /* DoubleClick(ULONG sSeconds, ULONG sMicros, ULONG cSeconds, ULONG cMicros) -> BOOL  [-102] */
        r->d[0] = (ULONG)DoubleClick((ULONG)r->d[0],
              (ULONG)r->d[1],
              (ULONG)r->d[2],
              (ULONG)r->d[3]);
        return 0;
    case 21:  /* GetDefPrefs(struct Preferences * prefbuffer, WORD size) -> struct Preferences *  [-126] */
    {
        ULONG emu_limit_1 = (ULONG)(UWORD)r->d[0];
        if (emu_limit_1 > M68K_Preferences_SIZEOF) emu_limit_1 = M68K_Preferences_SIZEOF;
        struct Preferences emu_struct_0;
        if (emu68k_require_guest_range(r->a[0], emu_limit_1,
                                         "GetDefPrefs.prefbuffer", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        APTR emu_result = (APTR)GetDefPrefs((struct Preferences *)&emu_struct_0,
              (WORD)emu_limit_1);
        memset(EMU_GPTR(guest0, r->a[0]), 0, emu_limit_1);
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_Preferences, EMU_NFIELDS(emu_fields_Preferences), emu_limit_1);
        r->d[0] = emu_result ? r->a[0] : 0;
            return 0;
    }
    case 22:  /* GetPrefs(struct Preferences * prefbuffer, WORD size) -> struct Preferences *  [-132] */
    {
        ULONG emu_limit_1 = (ULONG)(UWORD)r->d[0];
        if (emu_limit_1 > M68K_Preferences_SIZEOF) emu_limit_1 = M68K_Preferences_SIZEOF;
        struct Preferences emu_struct_0;
        if (emu68k_require_guest_range(r->a[0], emu_limit_1,
                                         "GetPrefs.prefbuffer", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        APTR emu_result = (APTR)GetPrefs((struct Preferences *)&emu_struct_0,
              (WORD)emu_limit_1);
        memset(EMU_GPTR(guest0, r->a[0]), 0, emu_limit_1);
        emu68k_to_guest_sized(guest0, r->a[0], &emu_struct_0,
                           emu_fields_Preferences, EMU_NFIELDS(emu_fields_Preferences), emu_limit_1);
        r->d[0] = emu_result ? r->a[0] : 0;
            return 0;
    }
    case 35:  /* OpenWorkBench(void) -> IPTR  [-210] */
        r->d[0] = (ULONG)OpenWorkBench();   /* narrowed: an integer, never an address */
        return 0;
    case 56:  /* WBenchToBack(void) -> BOOL  [-336] */
        r->d[0] = (ULONG)WBenchToBack();
        return 0;
    case 57:  /* WBenchToFront(void) -> BOOL  [-342] */
        r->d[0] = (ULONG)WBenchToFront();
        return 0;
    case 64:  /* RemakeDisplay(void) -> LONG  [-384] */
        r->d[0] = (ULONG)RemakeDisplay();
        return 0;
    case 65:  /* RethinkDisplay(void) -> LONG  [-390] */
        r->d[0] = (ULONG)RethinkDisplay();
        return 0;
    case 69:  /* LockIBase(ULONG What) -> ULONG  [-414] */
        r->d[0] = (ULONG)LockIBase((ULONG)r->d[0]);
        return 0;
    case 70:  /* UnlockIBase(ULONG ibLock) -> void  [-420] */
        UnlockIBase((ULONG)r->a[0]);
        return 0;
    case 85:  /* LockPubScreen(CONST_STRPTR name) -> struct Screen *  [-510] */
    {
        APTR emu_result = (APTR)LockPubScreen((CONST_STRPTR)EMU_GPTR(guest0, r->a[0]));
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_Screen,
                                             base, NULL,
                                             "Screen", 84,
                                             emu_fields_Screen, EMU_NFIELDS(emu_fields_Screen),
                                             &r->d[0], err, errlen) < 0)
            return 1;
        if (emu_result && r->d[0])
        {
            struct Screen *emu_facade_native = (struct Screen *)emu_result;
            ULONG emu_nested_token_0 =
                r->d[0] + M68K_Screen_ViewPort_Next;
            if (emu68k_object_alias_to_guest(guest0,
                    emu_nested_token_0, &emu_facade_native->ViewPort,
                    EMU_OBJ_ViewPort, "ViewPort", err, errlen) < 0)
                return 1;
            ULONG emu_nested_token_1 = 0;
            if (emu68k_object_to_guest(guest0,
                    emu_facade_native->ViewPort.ColorMap, EMU_OBJ_ColorMap,
                    NULL, NULL, "ColorMap",
                    &emu_nested_token_1, err, errlen) < 0)
                return 1;
            emu68k_scalar_to_guest(guest0,
                r->d[0] + M68K_Screen_ViewPort_ColorMap, 4, emu_nested_token_1);
        }
            return 0;
    }
    case 86:  /* UnlockPubScreen(UBYTE * name, struct Screen * screen) -> void  [-516] */
    {
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_Screen, 1,
                                        "Screen", &emu_object_1, err, errlen) < 0)
            return 1;
            UnlockPubScreen((UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (struct Screen *)emu_object_1);
        emu68k_object_release(guest0,
            r->a[1] + M68K_Screen_ViewPort_Next,
            EMU_OBJ_ViewPort);
        emu68k_object_release(guest0,
            (ULONG)emu68k_scalar_from_guest(guest0, r->a[1] + M68K_Screen_ViewPort_ColorMap, 4),
            EMU_OBJ_ColorMap);
        emu68k_object_release(guest0, r->a[1], EMU_OBJ_Screen);
            return 0;
    }
    case 88:  /* UnlockPubScreenList(void) -> void  [-528] */
        UnlockPubScreenList();
        return 0;
    case 90:  /* SetDefaultPubScreen(UBYTE * name) -> void  [-540] */
        SetDefaultPubScreen((UBYTE *)EMU_GPTR(guest0, r->a[0]));
        return 0;
    case 91:  /* SetPubScreenModes(UWORD modes) -> UWORD  [-546] */
        r->d[0] = (ULONG)SetPubScreenModes((UWORD)r->d[0]);
        return 0;
    case 92:  /* PubScreenStatus(struct Screen * Scr, UWORD StatusFlags) -> UWORD  [-552] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Screen, 0,
                                        "Screen", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)PubScreenStatus((struct Screen *)emu_object_0,
              (UWORD)r->d[0]);
            return 0;
    }
    case 102:  /* OpenScreenTagList(struct NewScreen * newScreen, struct TagItem * tagList) -> struct Screen *  [-612] */
    {
        if (r->a[0])
        {
            if (err && errlen)
                snprintf(err, errlen, "OpenScreenTagList.newScreen currently requires NULL");
            return 1;
        }
        struct TagItem emu_tags_1[25];
        ULONG emu_tagscratch_size_1 = sizeof(UQUAD) * ((sizeof(struct TextAttr) + 7) / 8 + (sizeof(UWORD) * 32 + 7) / 8 + (sizeof(ULONG) * 1024 + 7) / 8);
        APTR emu_tagscratch_1 = emu68k_scratch_alloc(emu_tagscratch_size_1, err, errlen);
        if (!emu_tagscratch_1)
            return 1;
        if (emu68k_tags_to_native(guest0, r->a[1], &emu_tagdomain_intuition_open_screen,
                                     emu_tags_1, 25, emu_tagscratch_1, emu_tagscratch_size_1, err, errlen) < 0)
        {
            emu68k_scratch_free(emu_tagscratch_1, emu_tagscratch_size_1);
            return 1;
        }
        APTR emu_result = (APTR)OpenScreenTagList((struct NewScreen *)NULL,
              (struct TagItem *)(r->a[1] ? emu_tags_1 : NULL));
        if (!emu_result)
        {
            BOOL emu_fallback_changed = FALSE;
            for (ULONG emu_fallback_i = 0;
                 emu_tags_1[emu_fallback_i].ti_Tag != TAG_DONE;
                 emu_fallback_i++)
                if (emu_tags_1[emu_fallback_i].ti_Tag == SA_Font)
                {
                    struct TextAttr *emu_fallback_value =
                        (struct TextAttr *)emu_tags_1[emu_fallback_i].ti_Data;
                    if (emu_fallback_value)
                    {
                        emu_fallback_value->ta_Name = (STRPTR)"Vera Mono.font";
                        emu_fallback_changed = TRUE;
                    }
                }
            if (emu_fallback_changed)
                emu_result = (APTR)OpenScreenTagList((struct NewScreen *)NULL,
              (struct TagItem *)(r->a[1] ? emu_tags_1 : NULL));
        }
        if (!emu_result)
        {
            BOOL emu_fallback_changed = FALSE;
            for (ULONG emu_fallback_i = 0;
                 emu_tags_1[emu_fallback_i].ti_Tag != TAG_DONE;
                 emu_fallback_i++)
                if (emu_tags_1[emu_fallback_i].ti_Tag == SA_DisplayID)
                {
                    emu_tags_1[emu_fallback_i].ti_Tag = TAG_IGNORE;
                    emu_fallback_changed = TRUE;
                }
            if (emu_fallback_changed)
                emu_result = (APTR)OpenScreenTagList((struct NewScreen *)NULL,
              (struct TagItem *)(r->a[1] ? emu_tags_1 : NULL));
        }
        emu68k_scratch_free(emu_tagscratch_1, emu_tagscratch_size_1);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_Screen,
                                             base, emu_object_cleanup_Screen,
                                             "Screen", 84,
                                             emu_fields_Screen, EMU_NFIELDS(emu_fields_Screen),
                                             &r->d[0], err, errlen) < 0)
            return 1;
        if (emu_result && r->d[0])
        {
            struct Screen *emu_facade_native = (struct Screen *)emu_result;
            ULONG emu_nested_token_0 =
                r->d[0] + M68K_Screen_ViewPort_Next;
            if (emu68k_object_alias_to_guest(guest0,
                    emu_nested_token_0, &emu_facade_native->ViewPort,
                    EMU_OBJ_ViewPort, "ViewPort", err, errlen) < 0)
                return 1;
            ULONG emu_nested_token_1 = 0;
            if (emu68k_object_to_guest(guest0,
                    emu_facade_native->ViewPort.ColorMap, EMU_OBJ_ColorMap,
                    NULL, NULL, "ColorMap",
                    &emu_nested_token_1, err, errlen) < 0)
                return 1;
            emu68k_scalar_to_guest(guest0,
                r->d[0] + M68K_Screen_ViewPort_ColorMap, 4, emu_nested_token_1);
        }
            return 0;
    }
    case 106:  /* NewObjectA(struct IClass * classPtr, UBYTE * classID, struct TagItem * tagList) -> APTR  [-636] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Class, 1,
                                        "Class", &emu_object_0, err, errlen) < 0)
            return 1;
        struct Emu68kBoopsiBridge emu_boopsi_0;
        struct TagItem emu_tags_2[33];
        UQUAD emu_tagscratch_2[(sizeof(struct BitMap) + 7) / 8];
        if (emu68k_tags_to_native(guest0, r->a[2], &emu_tagdomain_intuition_new_object,
                                     emu_tags_2, 33, emu_tagscratch_2, sizeof emu_tagscratch_2, err, errlen) < 0)
            return 1;
        if (emu68k_boopsi_prepare(guest0, r->a[0], emu_object_0,
                                   &emu_boopsi_0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)NewObjectA((struct IClass *)emu_object_0,
              (UBYTE *)EMU_GPTR(guest0, r->a[1]),
              (struct TagItem *)(r->a[2] ? emu_tags_2 : NULL));
        if (emu68k_boopsi_finish(&emu_boopsi_0, err, errlen) < 0)
            return 1;
        if (emu68k_object_to_guest(guest0, emu_result, EMU_OBJ_Object,
                                      base, emu_object_cleanup_Object,
                                      "Object", &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 107:  /* DisposeObject(APTR object) -> void  [-642] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Object, 1,
                                        "Object", &emu_object_0, err, errlen) < 0)
            return 1;
            DisposeObject((APTR)emu_object_0);
        emu68k_object_consume(guest0, r->a[0], EMU_OBJ_Object);
            return 0;
    }
    case 113:  /* MakeClass(ClassID classID, ClassID superClassID, struct IClass * superClassPtr, ULONG instanceSize, ULONG flags) -> struct IClass *  [-678] */
    {
        APTR emu_object_2;
        if (emu68k_object_from_guest(guest0, r->a[2], EMU_OBJ_Class, 1,
                                        "Class", &emu_object_2, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)MakeClass((ClassID)EMU_GPTR(guest0, r->a[0]),
              (ClassID)EMU_GPTR(guest0, r->a[1]),
              (struct IClass *)emu_object_2,
              (ULONG)r->d[0],
              (ULONG)r->d[1]);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_Class,
                                             base, emu_object_cleanup_Class,
                                             "Class", M68K_IClass_SIZEOF,
                                             emu_fields_IClass, EMU_NFIELDS(emu_fields_IClass),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 114:  /* AddClass(struct IClass * classPtr) -> void  [-684] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Class, 0,
                                        "Class", &emu_object_0, err, errlen) < 0)
            return 1;
            AddClass((struct IClass *)emu_object_0);
            return 0;
    }
    case 115:  /* GetScreenDrawInfo(struct Screen * screen) -> struct DrawInfo *  [-690] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Screen, 0,
                                        "Screen", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)GetScreenDrawInfo((struct Screen *)emu_object_0);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_DrawInfo,
                                             base, NULL,
                                             "DrawInfo", M68K_DrawInfo_SIZEOF + sizeof(UWORD) * 256,
                                             emu_fields_DrawInfo, EMU_NFIELDS(emu_fields_DrawInfo),
                                             &r->d[0], err, errlen) < 0)
            return 1;
        if (emu_result && r->d[0])
        {
            struct DrawInfo *emu_facade_native = (struct DrawInfo *)emu_result;
            ULONG emu_nested_count_0 = emu_facade_native->dri_NumPens;
            if (emu_nested_count_0 > 256 ||
                (emu_nested_count_0 && !emu_facade_native->dri_Pens))
            {
                if (err && errlen)
                    snprintf(err, errlen, "DrawInfo.dri_Pens has invalid count/pointer");
                return 1;
            }
            ULONG emu_nested_guest_0 = r->d[0] + M68K_DrawInfo_SIZEOF + sizeof(UWORD) * 256;
            for (ULONG emu_nested_i_0 = 0;
                 emu_nested_i_0 < emu_nested_count_0;
                 emu_nested_i_0++)
                emu68k_scalar_to_guest(guest0,
                    emu_nested_guest_0 + emu_nested_i_0 * 2, 2,
                    emu_facade_native->dri_Pens[emu_nested_i_0]);
            emu68k_scalar_to_guest(guest0,
                r->d[0] + M68K_DrawInfo_dri_Pens, 4,
                emu_nested_count_0 ? emu_nested_guest_0 : 0);
            ULONG emu_nested_token_1 = 0;
            if (emu68k_object_to_guest_facade(guest0,
                    emu_facade_native->dri_Font, EMU_OBJ_TextFont,
                    NULL, NULL, "TextFont", M68K_TextFont_SIZEOF,
                    emu_fields_TextFont, EMU_NFIELDS(emu_fields_TextFont),
                    &emu_nested_token_1, err, errlen) < 0)
                return 1;
            emu68k_scalar_to_guest(guest0,
                r->d[0] + M68K_DrawInfo_dri_Font, 4, emu_nested_token_1);
        }
            return 0;
    }
    case 116:  /* FreeScreenDrawInfo(struct Screen * screen, struct DrawInfo * drawInfo) -> void  [-696] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Screen, 0,
                                        "Screen", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_object_1;
        if (emu68k_object_from_guest(guest0, r->a[1], EMU_OBJ_DrawInfo, 0,
                                        "DrawInfo", &emu_object_1, err, errlen) < 0)
            return 1;
            FreeScreenDrawInfo((struct Screen *)emu_object_0,
              (struct DrawInfo *)emu_object_1);
        emu68k_object_release(guest0,
            (ULONG)emu68k_scalar_from_guest(guest0, r->a[1] + M68K_DrawInfo_dri_Font, 4),
            EMU_OBJ_TextFont);
        emu68k_object_release(guest0, r->a[1], EMU_OBJ_DrawInfo);
            return 0;
    }
    case 118:  /* RemoveClass(struct IClass * classPtr) -> void  [-708] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Class, 0,
                                        "Class", &emu_object_0, err, errlen) < 0)
            return 1;
            RemoveClass((struct IClass *)emu_object_0);
            return 0;
    }
    case 119:  /* FreeClass(struct IClass * iclass) -> BOOL  [-714] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->a[0], EMU_OBJ_Class, 0,
                                        "Class", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)FreeClass((struct IClass *)emu_object_0);
        emu68k_object_consume(guest0, r->a[0], EMU_OBJ_Class);
            return 0;
    }
    case 137:  /* TimedDisplayAlert(ULONG alertnumber, UBYTE * string, UWORD height, ULONG time) -> BOOL  [-822] */
        r->d[0] = (ULONG)TimedDisplayAlert((ULONG)r->d[0],
              (UBYTE *)EMU_GPTR(guest0, r->a[0]),
              (UWORD)r->d[1],
              (ULONG)r->a[1]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
