/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/iffparse/iffparse.conf - do not edit.
 *
 * Tier 1 crossings for iffparse.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/iffparse.h>

#include "emu68k_gen.h"

int emu68k_gen_iffparse(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct Library *IFFParseBase = base;
    (void)r; (void)guest0; (void)IFFParseBase;

    switch (lvo)
    {
    case 42:  /* GoodID(LONG id) -> LONG  [-252] */
        r->d[0] = (ULONG)GoodID((LONG)r->d[0]);
        return 0;
    case 43:  /* GoodType(LONG type) -> LONG  [-258] */
        r->d[0] = (ULONG)GoodType((LONG)r->d[0]);
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
