/* GENERATED by graft/gen-emu68k-bridge from workbench/libs/datatypes/datatypes.conf - do not edit.
 *
 * Derived crossings for datatypes.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/datatypes.h>

#include "emu68k_gen.h"

int emu68k_gen_datatypes(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct Library *DataTypesBase = base;
    (void)r; (void)guest0; (void)DataTypesBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 48:  /* GetDTTriggerMethodDataFlags(ULONG method) -> ULONG  [-288] */
        r->d[0] = (ULONG)GetDTTriggerMethodDataFlags((ULONG)r->a[0]);
        return 0;
    }
    return 1;   /* no safe generated crossing for this vector */
}
