/* GENERATED by graft/gen-emu68k-bridge from rom/exec/exec.conf - do not edit.
 *
 * Tier 1 crossings for exec.library: every argument is a scalar or a pointer to
 * bytes, and the result is a scalar, so the crossing follows entirely from
 * the vector's declared prototype and register mapping. Anything needing a
 * structure rebuilt, a BPTR mapped, or a callback into the guest is NOT
 * here: those are hand-written in emu68k_oscall.c.
 */

#include <exec/types.h>
#include <proto/exec.h>

#include "emu68k_gen.h"

int emu68k_gen_exec(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base)
{
    struct ExecBase *SysBase = base;
    (void)r; (void)guest0; (void)SysBase;

    switch (lvo)
    {
    case 36:  /* AvailMem(ULONG attributes) -> IPTR  [-216] */
        r->d[0] = (ULONG)AvailMem((ULONG)r->d[1]);   /* narrowed: an integer, never an address */
        return 0;
    }
    return 1;   /* not a tier-1 vector of this library */
}
