/* GENERATED by graft/gen-emu68k-bridge from rom/dos/dos.conf - do not edit.
 *
 * Derived crossings for dos.library. Tier-1 scalar/string calls come straight
 * from the .conf prototype and register map; type-sensitive calls additionally
 * consume the checked semantic policy in graft/emu68k-bridge-policy.json.
 * Anything still lacking policy remains unavailable rather than guessed.
 */

#include <exec/types.h>
#include <proto/dos.h>
#include <string.h>

#include "emu68k_gen.h"
#include "emu68k_layouts.h"

int emu68k_gen_dos(int lvo, struct Emu68kRegs *r, APTR guest0, APTR base,
                  char *err, ULONG errlen)
{
    struct DosLibrary *DOSBase = base;
    (void)r; (void)guest0; (void)DOSBase; (void)err; (void)errlen;

    switch (lvo)
    {
    case 1:  /* OpenLib: no crossing [-6] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.OpenLib needs private described");
        r->d[0] = 0;
        return 1;
    case 2:  /* CloseLib: no crossing [-12] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CloseLib needs private described");
        r->d[0] = 0;
        return 1;
    case 5:  /* Open(CONST_STRPTR name, LONG accessMode) -> BPTR  [-30] */
        r->d[0] = EMU_TOKEN(guest0, Open((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (LONG)r->d[2]));   /* a BPTR crosses as a token */
        return 0;
    case 6:  /* Close: no crossing [-36] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Close needs BPTR file described");
        r->d[0] = 0;
        return 1;
    case 7:  /* Read: no crossing [-42] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Read needs APTR buffer, BPTR file described");
        r->d[0] = 0;
        return 1;
    case 8:  /* Write: no crossing [-48] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Write needs APTR buffer, BPTR file described");
        r->d[0] = 0;
        return 1;
    case 9:  /* Input(void) -> BPTR  [-54] */
        r->d[0] = EMU_TOKEN(guest0, Input());   /* a BPTR crosses as a token */
        return 0;
    case 10:  /* Output(void) -> BPTR  [-60] */
        r->d[0] = EMU_TOKEN(guest0, Output());   /* a BPTR crosses as a token */
        return 0;
    case 11:  /* Seek(BPTR file, LONG position, LONG mode) -> LONG  [-66] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "Seek.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)Seek(emu_bptr_0,
              (LONG)r->d[2],
              (LONG)r->d[3]);
        return 0;
    }
    case 12:  /* DeleteFile(CONST_STRPTR name) -> BOOL  [-72] */
        r->d[0] = (ULONG)DeleteFile((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]));
        return 0;
    case 13:  /* Rename(CONST_STRPTR oldName, CONST_STRPTR newName) -> LONG  [-78] */
        r->d[0] = (ULONG)Rename((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 14:  /* Lock(CONST_STRPTR name, LONG accessMode) -> BPTR  [-84] */
        r->d[0] = EMU_TOKEN(guest0, Lock((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (LONG)r->d[2]));   /* a BPTR crosses as a token */
        return 0;
    case 15:  /* UnLock: no crossing [-90] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.UnLock needs BPTR lock described");
        r->d[0] = 0;
        return 1;
    case 16:  /* DupLock(BPTR lock) -> BPTR  [-96] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "DupLock.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, DupLock(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 17:  /* Examine(BPTR lock, struct FileInfoBlock* fib) -> LONG  [-102] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "Examine.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        struct FileInfoBlock emu_struct_1;
        if (!r->d[2])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: Examine.fib requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[2], M68K_FileInfoBlock_SIZEOF,
                                         "Examine.fib", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
            r->d[0] = (ULONG)Examine(emu_bptr_0,
              (struct FileInfoBlock*)&emu_struct_1);
        if (r->d[0])
        {
            memset(EMU_GPTR(guest0, r->d[2]), 0, M68K_FileInfoBlock_SIZEOF);
            emu68k_to_guest_sized(guest0, r->d[2], &emu_struct_1,
                               emu_fields_FileInfoBlock, EMU_NFIELDS(emu_fields_FileInfoBlock), M68K_FileInfoBlock_SIZEOF);
        }
            return 0;
    }
    case 18:  /* ExNext(BPTR lock, struct FileInfoBlock* fileInfoBlock) -> LONG  [-108] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "ExNext.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        struct FileInfoBlock emu_struct_1;
        if (!r->d[2])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: ExNext.fileInfoBlock requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[2], M68K_FileInfoBlock_SIZEOF,
                                         "ExNext.fileInfoBlock", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->d[2], &emu_struct_1,
                             emu_fields_FileInfoBlock, EMU_NFIELDS(emu_fields_FileInfoBlock), M68K_FileInfoBlock_SIZEOF);
            r->d[0] = (ULONG)ExNext(emu_bptr_0,
              (struct FileInfoBlock*)&emu_struct_1);
        if (r->d[0])
        {
            memset(EMU_GPTR(guest0, r->d[2]), 0, M68K_FileInfoBlock_SIZEOF);
            emu68k_to_guest_sized(guest0, r->d[2], &emu_struct_1,
                               emu_fields_FileInfoBlock, EMU_NFIELDS(emu_fields_FileInfoBlock), M68K_FileInfoBlock_SIZEOF);
        }
            return 0;
    }
    case 19:  /* Info(BPTR lock, struct InfoData* parameterBlock) -> LONG  [-114] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "Info.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        struct InfoData emu_struct_1;
        if (!r->d[2])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: Info.parameterBlock requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[2], M68K_InfoData_SIZEOF,
                                         "Info.parameterBlock", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
            r->d[0] = (ULONG)Info(emu_bptr_0,
              (struct InfoData*)&emu_struct_1);
        if (r->d[0])
        {
            memset(EMU_GPTR(guest0, r->d[2]), 0, M68K_InfoData_SIZEOF);
            emu68k_to_guest_sized(guest0, r->d[2], &emu_struct_1,
                               emu_fields_InfoData, EMU_NFIELDS(emu_fields_InfoData), M68K_InfoData_SIZEOF);
        }
            return 0;
    }
    case 20:  /* CreateDir(CONST_STRPTR name) -> BPTR  [-120] */
        r->d[0] = EMU_TOKEN(guest0, CreateDir((CONST_STRPTR)EMU_GPTR(guest0, r->d[1])));   /* a BPTR crosses as a token */
        return 0;
    case 21:  /* CurrentDir(BPTR lock) -> BPTR  [-126] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "CurrentDir.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, CurrentDir(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 22:  /* IoErr(void) -> SIPTR  [-132] */
        r->d[0] = (ULONG)IoErr();   /* narrowed: an integer, never an address */
        return 0;
    case 23:  /* CreateProc: no crossing [-138] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CreateProc needs returns a pointer (struct MsgPort*) described");
        r->d[0] = 0;
        return 1;
    case 24:  /* Exit: no crossing [-144] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Exit needs refused: the guest exits by returning, not by this described");
        r->d[0] = 0;
        return 1;
    case 25:  /* LoadSeg(CONST_STRPTR name) -> BPTR  [-150] */
        r->d[0] = EMU_TOKEN(guest0, LoadSeg((CONST_STRPTR)EMU_GPTR(guest0, r->d[1])));   /* a BPTR crosses as a token */
        return 0;
    case 26:  /* UnLoadSeg: no crossing [-156] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.UnLoadSeg needs BPTR seglist described");
        r->d[0] = 0;
        return 1;
    case 29:  /* DeviceProc: no crossing [-174] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.DeviceProc needs returns a pointer (struct MsgPort *) described");
        r->d[0] = 0;
        return 1;
    case 30:  /* SetComment(CONST_STRPTR name, CONST_STRPTR comment) -> LONG  [-180] */
        r->d[0] = (ULONG)SetComment((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 31:  /* SetProtection(CONST_STRPTR name, ULONG protect) -> LONG  [-186] */
        r->d[0] = (ULONG)SetProtection((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (ULONG)r->d[2]);
        return 0;
    case 32:  /* DateStamp(struct DateStamp * date) -> struct DateStamp *  [-192] */
    {
        struct DateStamp emu_struct_0;
        if (!r->d[1])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: DateStamp.date requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[1], M68K_DateStamp_SIZEOF,
                                         "DateStamp.date", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        APTR emu_result = (APTR)DateStamp((struct DateStamp *)&emu_struct_0);
        memset(EMU_GPTR(guest0, r->d[1]), 0, M68K_DateStamp_SIZEOF);
        emu68k_to_guest_sized(guest0, r->d[1], &emu_struct_0,
                           emu_fields_DateStamp, EMU_NFIELDS(emu_fields_DateStamp), M68K_DateStamp_SIZEOF);
        r->d[0] = emu_result ? r->d[1] : 0;
            return 0;
    }
    case 33:  /* Delay(ULONG timeout) -> void  [-198] */
        Delay((ULONG)r->d[1]);
        return 0;
    case 34:  /* WaitForChar(BPTR file, LONG timeout) -> LONG  [-204] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "WaitForChar.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)WaitForChar(emu_bptr_0,
              (LONG)r->d[2]);
        return 0;
    }
    case 35:  /* ParentDir(BPTR lock) -> BPTR  [-210] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "ParentDir.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, ParentDir(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 36:  /* IsInteractive(BPTR file) -> LONG  [-216] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "IsInteractive.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)IsInteractive(emu_bptr_0);
        return 0;
    }
    case 37:  /* Execute(CONST_STRPTR string, BPTR input, BPTR output) -> BOOL  [-222] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "Execute.input", &emu_bptr_1, err, errlen) < 0)
            return 1;
        BPTR emu_bptr_2;
        if (emu68k_handle_require(guest0, r->d[3],
                                 "Execute.output", &emu_bptr_2, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)Execute((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              emu_bptr_1,
              emu_bptr_2);
        return 0;
    }
    case 38:  /* AllocDosObject: no crossing [-228] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AllocDosObject needs returns a pointer (APTR) described");
        r->d[0] = 0;
        return 1;
    case 39:  /* FreeDosObject: no crossing [-234] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FreeDosObject needs APTR ptr described");
        r->d[0] = 0;
        return 1;
    case 40:  /* DoPkt(struct MsgPort* port, LONG action, SIPTR arg1, SIPTR arg2, SIPTR arg3, SIPTR arg4, SIPTR arg5) -> SIPTR  [-240] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->d[1], EMU_OBJ_MsgPort, 1,
                                        "MsgPort", &emu_object_0, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)DoPkt((struct MsgPort*)emu_object_0,
              (LONG)r->d[2],
              (SIPTR)(LONG)r->d[3],
              (SIPTR)(LONG)r->d[4],
              (SIPTR)(LONG)r->d[5],
              (SIPTR)(LONG)r->d[6],
              (SIPTR)(LONG)r->d[7]);   /* narrowed: an integer, never an address */
            return 0;
    }
    case 41:  /* SendPkt: no crossing [-246] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SendPkt needs struct DosPacket *, struct MsgPort * described");
        r->d[0] = 0;
        return 1;
    case 42:  /* WaitPkt: no crossing [-252] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.WaitPkt needs returns a pointer (struct DosPacket *) described");
        r->d[0] = 0;
        return 1;
    case 43:  /* ReplyPkt: no crossing [-258] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ReplyPkt needs struct DosPacket * described");
        r->d[0] = 0;
        return 1;
    case 44:  /* AbortPkt: no crossing [-264] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AbortPkt needs struct DosPacket *, struct MsgPort * described");
        r->d[0] = 0;
        return 1;
    case 45:  /* LockRecord(BPTR fh, ULONG offset, ULONG length, ULONG mode, ULONG timeout) -> BOOL  [-270] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "LockRecord.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)LockRecord(emu_bptr_0,
              (ULONG)r->d[2],
              (ULONG)r->d[3],
              (ULONG)r->d[4],
              (ULONG)r->d[5]);
        return 0;
    }
    case 46:  /* LockRecords: no crossing [-276] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.LockRecords needs struct RecordLock * described");
        r->d[0] = 0;
        return 1;
    case 47:  /* UnLockRecord(BPTR fh, ULONG offset, ULONG length) -> BOOL  [-282] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "UnLockRecord.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)UnLockRecord(emu_bptr_0,
              (ULONG)r->d[2],
              (ULONG)r->d[3]);
        return 0;
    }
    case 48:  /* UnLockRecords: no crossing [-288] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.UnLockRecords needs struct RecordLock * described");
        r->d[0] = 0;
        return 1;
    case 49:  /* SelectInput(BPTR fh) -> BPTR  [-294] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SelectInput.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, SelectInput(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 50:  /* SelectOutput(BPTR fh) -> BPTR  [-300] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SelectOutput.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, SelectOutput(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 51:  /* FGetC(BPTR file) -> LONG  [-306] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "FGetC.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)FGetC(emu_bptr_0);
        return 0;
    }
    case 52:  /* FPutC(BPTR file, LONG character) -> LONG  [-312] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "FPutC.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)FPutC(emu_bptr_0,
              (LONG)r->d[2]);
        return 0;
    }
    case 53:  /* UnGetC(BPTR file, LONG character) -> LONG  [-318] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "UnGetC.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)UnGetC(emu_bptr_0,
              (LONG)r->d[2]);
        return 0;
    }
    case 54:  /* FRead: no crossing [-324] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FRead needs APTR block, BPTR fh described");
        r->d[0] = 0;
        return 1;
    case 55:  /* FWrite: no crossing [-330] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FWrite needs APTR block, BPTR fh described");
        r->d[0] = 0;
        return 1;
    case 56:  /* FGets: no crossing [-336] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FGets needs returns a pointer (STRPTR) described");
        r->d[0] = 0;
        return 1;
    case 57:  /* FPuts(BPTR file, CONST_STRPTR string) -> LONG  [-342] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "FPuts.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)FPuts(emu_bptr_0,
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    }
    case 58:  /* VFWritef: no crossing [-348] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.VFWritef needs BPTR fh, RAWARG argarray described");
        r->d[0] = 0;
        return 1;
    case 59:  /* VFPrintf: no crossing [-354] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.VFPrintf needs BPTR file, RAWARG argarray described");
        r->d[0] = 0;
        return 1;
    case 60:  /* Flush(BPTR file) -> LONG  [-360] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "Flush.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)Flush(emu_bptr_0);
        return 0;
    }
    case 61:  /* SetVBuf(BPTR file, STRPTR buff, LONG type, LONG size) -> LONG  [-366] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SetVBuf.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)SetVBuf(emu_bptr_0,
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3],
              (LONG)r->d[4]);
        return 0;
    }
    case 62:  /* DupLockFromFH(BPTR lock) -> BPTR  [-372] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "DupLockFromFH.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, DupLockFromFH(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 63:  /* OpenFromLock(BPTR lock) -> BPTR  [-378] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "OpenFromLock.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, OpenFromLock(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 64:  /* ParentOfFH(BPTR fh) -> BPTR  [-384] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "ParentOfFH.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, ParentOfFH(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 65:  /* ExamineFH: no crossing [-390] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ExamineFH needs BPTR fh, struct FileInfoBlock* described");
        r->d[0] = 0;
        return 1;
    case 66:  /* SetFileDate: no crossing [-396] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetFileDate needs const struct DateStamp * described");
        r->d[0] = 0;
        return 1;
    case 67:  /* NameFromLock(BPTR lock, STRPTR buffer, LONG length) -> BOOL  [-402] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "NameFromLock.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)NameFromLock(emu_bptr_0,
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3]);
        return 0;
    }
    case 68:  /* NameFromFH(BPTR fh, STRPTR buffer, LONG length) -> BOOL  [-408] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "NameFromFH.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)NameFromFH(emu_bptr_0,
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3]);
        return 0;
    }
    case 69:  /* SplitName(CONST_STRPTR name, ULONG separator, STRPTR buf, LONG oldpos, LONG size) -> LONG  [-414] */
        r->d[0] = (ULONG)SplitName((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (ULONG)r->d[2],
              (STRPTR)EMU_GPTR(guest0, r->d[3]),
              (LONG)r->d[4],
              (LONG)r->d[5]);
        return 0;
    case 70:  /* SameLock(BPTR lock1, BPTR lock2) -> LONG  [-420] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SameLock.lock1", &emu_bptr_0, err, errlen) < 0)
            return 1;
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "SameLock.lock2", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)SameLock(emu_bptr_0,
              emu_bptr_1);
        return 0;
    }
    case 71:  /* SetMode(BPTR fh, LONG mode) -> LONG  [-426] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SetMode.fh", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)SetMode(emu_bptr_0,
              (LONG)r->d[2]);
        return 0;
    }
    case 72:  /* ExAll: no crossing [-432] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ExAll needs BPTR lock, struct ExAllControl *, struct ExAllData * described");
        r->d[0] = 0;
        return 1;
    case 73:  /* ReadLink: no crossing [-438] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ReadLink needs BPTR lock, struct MsgPort * described");
        r->d[0] = 0;
        return 1;
    case 74:  /* MakeLink: no crossing [-444] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.MakeLink needs refused: dest is a string or a lock depending on soft described");
        r->d[0] = 0;
        return 1;
    case 75:  /* ChangeMode(ULONG type, BPTR object, ULONG newmode) -> BOOL  [-450] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "ChangeMode.object", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)ChangeMode((ULONG)r->d[1],
              emu_bptr_1,
              (ULONG)r->d[3]);
        return 0;
    }
    case 76:  /* SetFileSize(BPTR file, LONG offset, LONG mode) -> LONG  [-456] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SetFileSize.file", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)SetFileSize(emu_bptr_0,
              (LONG)r->d[2],
              (LONG)r->d[3]);
        return 0;
    }
    case 77:  /* SetIoErr(SIPTR result) -> SIPTR  [-462] */
        r->d[0] = (ULONG)SetIoErr((SIPTR)(LONG)r->d[1]);   /* narrowed: an integer, never an address */
        return 0;
    case 78:  /* Fault(LONG code, CONST_STRPTR header, STRPTR buffer, LONG len) -> BOOL  [-468] */
        r->d[0] = (ULONG)Fault((LONG)r->d[1],
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]),
              (STRPTR)EMU_GPTR(guest0, r->d[3]),
              (LONG)r->d[4]);
        return 0;
    case 79:  /* PrintFault(LONG code, CONST_STRPTR header) -> BOOL  [-474] */
        r->d[0] = (ULONG)PrintFault((LONG)r->d[1],
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 80:  /* ErrorReport(LONG code, LONG type, IPTR arg1, struct MsgPort * device) -> BOOL  [-480] */
    {
        APTR emu_object_3;
        if (emu68k_object_from_guest(guest0, r->d[4], EMU_OBJ_MsgPort, 1,
                                        "MsgPort", &emu_object_3, err, errlen) < 0)
            return 1;
            r->d[0] = (ULONG)ErrorReport((LONG)r->d[1],
              (LONG)r->d[2],
              (IPTR)(LONG)r->d[3],
              (struct MsgPort *)emu_object_3);
            return 0;
    }
    case 81:  /* DisplayError: no crossing [-486] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.DisplayError needs APTR args described");
        r->d[0] = 0;
        return 1;
    case 82:  /* Cli: no crossing [-492] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Cli needs returns a pointer (struct CommandLineInterface *) described");
        r->d[0] = 0;
        return 1;
    case 83:  /* CreateNewProc: no crossing [-498] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CreateNewProc needs returns a pointer (struct Process *) described");
        r->d[0] = 0;
        return 1;
    case 84:  /* RunCommand: no crossing [-504] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.RunCommand needs BPTR segList described");
        r->d[0] = 0;
        return 1;
    case 85:  /* GetConsoleTask: no crossing [-510] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.GetConsoleTask needs returns a pointer (struct MsgPort *) described");
        r->d[0] = 0;
        return 1;
    case 86:  /* SetConsoleTask(struct MsgPort * handler) -> struct MsgPort *  [-516] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->d[1], EMU_OBJ_MsgPort, 1,
                                        "MsgPort", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)SetConsoleTask((struct MsgPort *)emu_object_0);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_MsgPort,
                                             base, NULL,
                                             "MsgPort", M68K_MsgPort_SIZEOF,
                                             emu_fields_MsgPort, EMU_NFIELDS(emu_fields_MsgPort),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 87:  /* GetFileSysTask: no crossing [-522] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.GetFileSysTask needs returns a pointer (struct MsgPort *) described");
        r->d[0] = 0;
        return 1;
    case 88:  /* SetFileSysTask(struct MsgPort * task) -> struct MsgPort *  [-528] */
    {
        APTR emu_object_0;
        if (emu68k_object_from_guest(guest0, r->d[1], EMU_OBJ_MsgPort, 1,
                                        "MsgPort", &emu_object_0, err, errlen) < 0)
            return 1;
        APTR emu_result = (APTR)SetFileSysTask((struct MsgPort *)emu_object_0);
        if (emu68k_object_to_guest_facade(guest0, emu_result, EMU_OBJ_MsgPort,
                                             base, NULL,
                                             "MsgPort", M68K_MsgPort_SIZEOF,
                                             emu_fields_MsgPort, EMU_NFIELDS(emu_fields_MsgPort),
                                             &r->d[0], err, errlen) < 0)
            return 1;
            return 0;
    }
    case 89:  /* GetArgStr: no crossing [-534] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.GetArgStr needs returns a pointer (STRPTR) described");
        r->d[0] = 0;
        return 1;
    case 90:  /* SetArgStr: no crossing [-540] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetArgStr needs refused: rebinds the host process argument string described");
        r->d[0] = 0;
        return 1;
    case 91:  /* FindCliProc: no crossing [-546] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FindCliProc needs returns a pointer (struct Process *) described");
        r->d[0] = 0;
        return 1;
    case 92:  /* MaxCli: no crossing [-552] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.MaxCli needs refused: reports on host CLIs, not guest ones described");
        r->d[0] = 0;
        return 1;
    case 93:  /* SetCurrentDirName: no crossing [-558] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetCurrentDirName needs refused: moves the host process, not the guest described");
        r->d[0] = 0;
        return 1;
    case 94:  /* GetCurrentDirName(STRPTR buf, LONG len) -> BOOL  [-564] */
        r->d[0] = (ULONG)GetCurrentDirName((STRPTR)EMU_GPTR(guest0, r->d[1]),
              (LONG)r->d[2]);
        return 0;
    case 95:  /* SetProgramName: no crossing [-570] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetProgramName needs refused: renames the host process described");
        r->d[0] = 0;
        return 1;
    case 96:  /* GetProgramName(STRPTR buf, LONG len) -> BOOL  [-576] */
        r->d[0] = (ULONG)GetProgramName((STRPTR)EMU_GPTR(guest0, r->d[1]),
              (LONG)r->d[2]);
        return 0;
    case 97:  /* SetPrompt: no crossing [-582] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetPrompt needs refused: the host shell's prompt is not the guest's described");
        r->d[0] = 0;
        return 1;
    case 98:  /* GetPrompt(STRPTR buf, LONG len) -> BOOL  [-588] */
        r->d[0] = (ULONG)GetPrompt((STRPTR)EMU_GPTR(guest0, r->d[1]),
              (LONG)r->d[2]);
        return 0;
    case 99:  /* SetProgramDir(BPTR lock) -> BPTR  [-594] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SetProgramDir.lock", &emu_bptr_0, err, errlen) < 0)
            return 1;
        r->d[0] = EMU_TOKEN(guest0, SetProgramDir(emu_bptr_0));   /* a BPTR crosses as a token */
        return 0;
    }
    case 100:  /* GetProgramDir(void) -> BPTR  [-600] */
        r->d[0] = EMU_TOKEN(guest0, GetProgramDir());   /* a BPTR crosses as a token */
        return 0;
    case 101:  /* SystemTagList: no crossing [-606] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SystemTagList needs const struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 102:  /* AssignLock(CONST_STRPTR name, BPTR lock) -> LONG  [-612] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "AssignLock.lock", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)AssignLock((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              emu_bptr_1);
        return 0;
    }
    case 103:  /* AssignLate(CONST_STRPTR name, CONST_STRPTR path) -> BOOL  [-618] */
        r->d[0] = (ULONG)AssignLate((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 104:  /* AssignPath(CONST_STRPTR name, CONST_STRPTR path) -> BOOL  [-624] */
        r->d[0] = (ULONG)AssignPath((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 105:  /* AssignAdd(CONST_STRPTR name, BPTR lock) -> BOOL  [-630] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "AssignAdd.lock", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)AssignAdd((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              emu_bptr_1);
        return 0;
    }
    case 106:  /* RemAssignList(CONST_STRPTR name, BPTR lock) -> LONG  [-636] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "RemAssignList.lock", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)RemAssignList((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              emu_bptr_1);
        return 0;
    }
    case 107:  /* GetDeviceProc: no crossing [-642] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.GetDeviceProc needs returns a pointer (struct DevProc *) described");
        r->d[0] = 0;
        return 1;
    case 108:  /* FreeDeviceProc: no crossing [-648] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FreeDeviceProc needs struct DevProc * described");
        r->d[0] = 0;
        return 1;
    case 109:  /* LockDosList: no crossing [-654] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.LockDosList needs returns a pointer (struct DosList *) described");
        r->d[0] = 0;
        return 1;
    case 110:  /* UnLockDosList: no crossing [-660] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.UnLockDosList needs refused: pairs with LockDosList, which is not tier 1 described");
        r->d[0] = 0;
        return 1;
    case 111:  /* AttemptLockDosList: no crossing [-666] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AttemptLockDosList needs returns a pointer (struct DosList *) described");
        r->d[0] = 0;
        return 1;
    case 112:  /* RemDosEntry: no crossing [-672] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.RemDosEntry needs struct DosList * described");
        r->d[0] = 0;
        return 1;
    case 113:  /* AddDosEntry: no crossing [-678] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AddDosEntry needs struct DosList * described");
        r->d[0] = 0;
        return 1;
    case 114:  /* FindDosEntry: no crossing [-684] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FindDosEntry needs returns a pointer (struct DosList *) described");
        r->d[0] = 0;
        return 1;
    case 115:  /* NextDosEntry: no crossing [-690] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.NextDosEntry needs returns a pointer (struct DosList *) described");
        r->d[0] = 0;
        return 1;
    case 116:  /* MakeDosEntry: no crossing [-696] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.MakeDosEntry needs returns a pointer (struct DosList *) described");
        r->d[0] = 0;
        return 1;
    case 117:  /* FreeDosEntry: no crossing [-702] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FreeDosEntry needs struct DosList * described");
        r->d[0] = 0;
        return 1;
    case 118:  /* IsFileSystem(CONST_STRPTR devicename) -> BOOL  [-708] */
        r->d[0] = (ULONG)IsFileSystem((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]));
        return 0;
    case 119:  /* Format: no crossing [-714] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Format needs refused: device-level, and destroys a volume described");
        r->d[0] = 0;
        return 1;
    case 120:  /* Relabel: no crossing [-720] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Relabel needs refused: device-level described");
        r->d[0] = 0;
        return 1;
    case 121:  /* Inhibit: no crossing [-726] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.Inhibit needs refused: device-level described");
        r->d[0] = 0;
        return 1;
    case 122:  /* AddBuffers: no crossing [-732] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AddBuffers needs refused: device-level described");
        r->d[0] = 0;
        return 1;
    case 123:  /* CompareDates(const struct DateStamp * date1, const struct DateStamp * date2) -> LONG  [-738] */
    {
        struct DateStamp emu_struct_0;
        if (!r->d[1])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: CompareDates.date1 requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[1], M68K_DateStamp_SIZEOF,
                                         "CompareDates.date1", err, errlen) < 0)
            return 1;
        memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->d[1], &emu_struct_0,
                             emu_fields_DateStamp, EMU_NFIELDS(emu_fields_DateStamp), M68K_DateStamp_SIZEOF);
        struct DateStamp emu_struct_1;
        if (!r->d[2])
        {
            if (err && errlen)
                snprintf(err, errlen, "capability gap: CompareDates.date2 requires a structure");
            return 1;
        }
        if (emu68k_require_guest_range(r->d[2], M68K_DateStamp_SIZEOF,
                                         "CompareDates.date2", err, errlen) < 0)
            return 1;
        memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->d[2], &emu_struct_1,
                             emu_fields_DateStamp, EMU_NFIELDS(emu_fields_DateStamp), M68K_DateStamp_SIZEOF);
            r->d[0] = (ULONG)CompareDates((const struct DateStamp *)&emu_struct_0,
              (const struct DateStamp *)&emu_struct_1);
            return 0;
    }
    case 124:  /* DateToStr: no crossing [-744] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.DateToStr needs struct DateTime * described");
        r->d[0] = 0;
        return 1;
    case 125:  /* StrToDate: no crossing [-750] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.StrToDate needs struct DateTime * described");
        r->d[0] = 0;
        return 1;
    case 126:  /* InternalLoadSeg: no crossing [-756] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.InternalLoadSeg needs BPTR fh, BPTR table, LONG *, LONG_FUNC * described");
        r->d[0] = 0;
        return 1;
    case 127:  /* InternalUnLoadSeg: no crossing [-762] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.InternalUnLoadSeg needs BPTR seglist, VOID_FUNC freefunc described");
        r->d[0] = 0;
        return 1;
    case 128:  /* NewLoadSeg: no crossing [-768] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.NewLoadSeg needs const struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 129:  /* AddSegment: no crossing [-774] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.AddSegment needs BPTR seg described");
        r->d[0] = 0;
        return 1;
    case 130:  /* FindSegment: no crossing [-780] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FindSegment needs returns a pointer (struct Segment *) described");
        r->d[0] = 0;
        return 1;
    case 131:  /* RemSegment: no crossing [-786] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.RemSegment needs struct Segment * described");
        r->d[0] = 0;
        return 1;
    case 132:  /* CheckSignal: no crossing [-792] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CheckSignal needs refused: the host task's signals are not the guest's described");
        r->d[0] = 0;
        return 1;
    case 133:  /* ReadArgs: no crossing [-798] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ReadArgs needs returns a pointer (struct RDArgs *) described");
        r->d[0] = 0;
        return 1;
    case 134:  /* FindArg(CONST_STRPTR templ, CONST_STRPTR keyword) -> LONG  [-804] */
        r->d[0] = (ULONG)FindArg((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 135:  /* ReadItem: no crossing [-810] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ReadItem needs struct CSource * described");
        r->d[0] = 0;
        return 1;
    case 136:  /* StrToLong: no crossing [-816] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.StrToLong needs LONG * described");
        r->d[0] = 0;
        return 1;
    case 137:  /* MatchFirst(CONST_STRPTR pat, struct AnchorPath * AP) -> LONG  [-822] */
    {
        struct AnchorPath emu_struct_1;
        struct AnchorPath *emu_structp_1 = NULL;
        if (r->d[2])
        {
            emu_structp_1 = &emu_struct_1;
            if (emu68k_require_guest_range(r->d[2], M68K_AnchorPath_SIZEOF,
                                             "MatchFirst.AP", err, errlen) < 0)
                return 1;
            memset(&emu_struct_1, 0, sizeof(emu_struct_1));
        emu68k_from_guest_sized(guest0, r->d[2], &emu_struct_1,
                             emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            r->d[0] = (ULONG)MatchFirst((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (struct AnchorPath *)emu_structp_1);
        if (emu_structp_1)
        {
            emu68k_to_guest_sized(guest0, r->d[2], &emu_struct_1,
                               emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            return 0;
    }
    case 138:  /* MatchNext(struct AnchorPath * AP) -> LONG  [-828] */
    {
        struct AnchorPath emu_struct_0;
        struct AnchorPath *emu_structp_0 = NULL;
        if (r->d[1])
        {
            emu_structp_0 = &emu_struct_0;
            if (emu68k_require_guest_range(r->d[1], M68K_AnchorPath_SIZEOF,
                                             "MatchNext.AP", err, errlen) < 0)
                return 1;
            memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->d[1], &emu_struct_0,
                             emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            r->d[0] = (ULONG)MatchNext((struct AnchorPath *)emu_structp_0);
        if (emu_structp_0)
        {
            emu68k_to_guest_sized(guest0, r->d[1], &emu_struct_0,
                               emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            return 0;
    }
    case 139:  /* MatchEnd(struct AnchorPath * AP) -> void  [-834] */
    {
        struct AnchorPath emu_struct_0;
        struct AnchorPath *emu_structp_0 = NULL;
        if (r->d[1])
        {
            emu_structp_0 = &emu_struct_0;
            if (emu68k_require_guest_range(r->d[1], M68K_AnchorPath_SIZEOF,
                                             "MatchEnd.AP", err, errlen) < 0)
                return 1;
            memset(&emu_struct_0, 0, sizeof(emu_struct_0));
        emu68k_from_guest_sized(guest0, r->d[1], &emu_struct_0,
                             emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            MatchEnd((struct AnchorPath *)emu_structp_0);
        if (emu_structp_0)
        {
            emu68k_to_guest_sized(guest0, r->d[1], &emu_struct_0,
                               emu_fields_AnchorPath, EMU_NFIELDS(emu_fields_AnchorPath), M68K_AnchorPath_SIZEOF);
        }
            return 0;
    }
    case 140:  /* ParsePattern(CONST_STRPTR Source, STRPTR Dest, LONG DestLength) -> LONG  [-840] */
        r->d[0] = (ULONG)ParsePattern((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3]);
        return 0;
    case 141:  /* MatchPattern(CONST_STRPTR pat, CONST_STRPTR str) -> BOOL  [-846] */
        r->d[0] = (ULONG)MatchPattern((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 143:  /* FreeArgs: no crossing [-858] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FreeArgs needs struct RDArgs * described");
        r->d[0] = 0;
        return 1;
    case 145:  /* FilePart: no crossing [-870] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FilePart needs returns a pointer (STRPTR) described");
        r->d[0] = 0;
        return 1;
    case 146:  /* PathPart: no crossing [-876] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.PathPart needs returns a pointer (STRPTR) described");
        r->d[0] = 0;
        return 1;
    case 147:  /* AddPart(STRPTR dirname, CONST_STRPTR filename, ULONG size) -> BOOL  [-882] */
        r->d[0] = (ULONG)AddPart((STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]),
              (ULONG)r->d[3]);
        return 0;
    case 148:  /* StartNotify: no crossing [-888] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.StartNotify needs struct NotifyRequest * described");
        r->d[0] = 0;
        return 1;
    case 149:  /* EndNotify: no crossing [-894] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.EndNotify needs struct NotifyRequest * described");
        r->d[0] = 0;
        return 1;
    case 150:  /* SetVar(CONST_STRPTR name, CONST_STRPTR buffer, LONG size, LONG flags) -> BOOL  [-900] */
        r->d[0] = (ULONG)SetVar((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3],
              (LONG)r->d[4]);
        return 0;
    case 151:  /* GetVar(CONST_STRPTR name, STRPTR buffer, LONG size, LONG flags) -> LONG  [-906] */
        r->d[0] = (ULONG)GetVar((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3],
              (LONG)r->d[4]);
        return 0;
    case 152:  /* DeleteVar(CONST_STRPTR name, ULONG flags) -> LONG  [-912] */
        r->d[0] = (ULONG)DeleteVar((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (ULONG)r->d[2]);
        return 0;
    case 153:  /* FindVar: no crossing [-918] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.FindVar needs returns a pointer (struct LocalVar *) described");
        r->d[0] = 0;
        return 1;
    case 154:  /* CliInit: no crossing [-924] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CliInit needs struct DosPacket * described");
        r->d[0] = 0;
        return 1;
    case 155:  /* CliInitNewcli: no crossing [-930] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CliInitNewcli needs struct DosPacket * described");
        r->d[0] = 0;
        return 1;
    case 156:  /* CliInitRun: no crossing [-936] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.CliInitRun needs struct DosPacket * described");
        r->d[0] = 0;
        return 1;
    case 157:  /* WriteChars(CONST_STRPTR buf, ULONG buflen) -> LONG  [-942] */
        r->d[0] = (ULONG)WriteChars((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (ULONG)r->d[2]);
        return 0;
    case 158:  /* PutStr(CONST_STRPTR string) -> LONG  [-948] */
        r->d[0] = (ULONG)PutStr((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]));
        return 0;
    case 159:  /* VPrintf: no crossing [-954] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.VPrintf needs RAWARG argarray described");
        r->d[0] = 0;
        return 1;
    case 161:  /* ParsePatternNoCase(CONST_STRPTR Source, STRPTR Dest, LONG DestLength) -> LONG  [-966] */
        r->d[0] = (ULONG)ParsePatternNoCase((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (STRPTR)EMU_GPTR(guest0, r->d[2]),
              (LONG)r->d[3]);
        return 0;
    case 162:  /* MatchPatternNoCase(CONST_STRPTR pat, CONST_STRPTR str) -> BOOL  [-972] */
        r->d[0] = (ULONG)MatchPatternNoCase((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              (CONST_STRPTR)EMU_GPTR(guest0, r->d[2]));
        return 0;
    case 163:  /* DosGetString: no crossing [-978] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.DosGetString needs returns a pointer (STRPTR) described");
        r->d[0] = 0;
        return 1;
    case 164:  /* SameDevice(BPTR lock1, BPTR lock2) -> BOOL  [-984] */
    {
        BPTR emu_bptr_0;
        if (emu68k_handle_require(guest0, r->d[1],
                                 "SameDevice.lock1", &emu_bptr_0, err, errlen) < 0)
            return 1;
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "SameDevice.lock2", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)SameDevice(emu_bptr_0,
              emu_bptr_1);
        return 0;
    }
    case 165:  /* ExAllEnd: no crossing [-990] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ExAllEnd needs BPTR lock, struct ExAllControl *, struct ExAllData * described");
        r->d[0] = 0;
        return 1;
    case 166:  /* SetOwner: no crossing [-996] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.SetOwner needs refused: device-level described");
        r->d[0] = 0;
        return 1;
    case 169:  /* ScanVars: no crossing [-1014] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.ScanVars needs APTR userdata, struct Hook * described");
        r->d[0] = 0;
        return 1;
    case 196:  /* GetSegListInfo: no crossing [-1176] */
        if (err && errlen)
            snprintf(err, errlen, "capability gap: dos.library.GetSegListInfo needs BPTR seglist, const struct TagItem * described");
        r->d[0] = 0;
        return 1;
    case 226:  /* AssignAddToList(CONST_STRPTR name, BPTR lock, ULONG position) -> BOOL  [-1356] */
    {
        BPTR emu_bptr_1;
        if (emu68k_handle_require(guest0, r->d[2],
                                 "AssignAddToList.lock", &emu_bptr_1, err, errlen) < 0)
            return 1;
        r->d[0] = (ULONG)AssignAddToList((CONST_STRPTR)EMU_GPTR(guest0, r->d[1]),
              emu_bptr_1,
              (ULONG)r->d[3]);
        return 0;
    }
    }
    return 1;   /* no safe generated crossing for this vector */
}
