##begin config
basename        memdisk
version         41.1
libbasetype     struct MemDiskBase
libbase         MemDiskBase
residentpri     10
beginio_func    BeginIO
abortio_func    AbortIO
options         noexpunge
##end config

##begin cdefprivate
#include "memdisk_intern.h"
##end cdefprivate

##begin cdef
#include <exec/devices.h>
#include <exec/io.h>
##end cdef
